project:
  type: website
  output-dir: docs
  
website:
  title: "OMC Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - students.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

