project:
  type: website
  output-dir: docs

#  pre-render: scripts/generate_members.R

website:
  title: "Castro-Medina Lab"
  favicon: images/logo-bpewg.svg
  description: "The Medina-Castro Laboratory is a network of scholars doing research in the field of Immunology"
  navbar:
    logo: images/mcl.png
    logo-alt: "Research Group in Mexico"
    pinned: true
    right:
      - href: index.qmd
        text: About
      - href: members.qmd
        text: Members
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: news.qmd
        text: News
      - href: protocols.qmd
        text: Protocols
  page-footer:
   right: 
    - text: "by おすかーる"
      href: https://omclab.org
    - text: "& ふぶき"
   center:
    - text: '<img src="/images/icons/codeberg.svg" alt="Codeberg" style="height:1em; vertical-align:middle; margin-right:0.5em"> View source code'
      href: https://codeberg.org/
    - text: "Report an issue"
      href: (mailto:omc@omclab.org)
  announcement: 
    content: "<span class=\"announcement-icon\" aria-hidden=\"true\"></span> we are going to the 48th ESPEN Congress 2026 in Berlin, Germany, and the International Congress on Obesity (ICO 2026) in Mexico City (see details [here](/news/ico26.qmd) and [here](/news/espen26.qmd))"
    dismissable: true
    position: below-navbar

format:
  html:
    theme:
      - yeti # pulse lumen cerulean spacelab yeti 
    grid:
      body-width: 1200px
      margin-width: 200px
      gutter-width: 1.5rem
    css: styles.css
    toc: true

bibliography: publications.bib

filters:
  - auto-dark


