---
title: "Medina-Castro Lab"
---

### The intestinal immune system in cancer and immune regulation

Standing at the intersection of Nutrition, Proteomics, and Immunology, our lab studies mucosal regulation in cancer, inflammation, and immunity. Intestinal immune homeostasis is maintained by a fine balance between the pro- and anti-inflammatory responses to microbiota. An extensive network of antigen presenting cells and effector cells tightly regulate these responses. We focus primarily on 1) the role of nutrition on immune responses and 2) macrophages regulation of intestinal T cells and epithelial cells, in health and disease.

Our group employs clinical interventions, immuno-proteomic, flow cytometry, proteomics and genomic methods, cell biology, biochemistry and *in vivo* models to reveal new intestinal immune regulation mechanisms.

We combine our expertise to gain novel insight on basic research questions, and we aim for translating our findings into clinical applications and therapeutic interventions to promote human health.

Our most recent papers are:

::: callout-important
## [Quality of life but not cachexia definitions are associated with overall survival in women with cervical cancer: a STROBE-compliant cohort study](https://academic.oup.com/jjco/article/54/4/416/7492484)

Luvián-Morales J, Delgadillo-González M, Castro-Eguiluz D, Oñate-Ocaña LF, Cetina-Pérez L\
*Jpn J Clin Oncol* 54(4):416-423\
doi 10.1093/jjco/hyae023, [PubMed](https://pubmed.ncbi.nlm.nih.gov/38146122/)

Gut microbiota plays a crucial role in modulating immune responses, including effector response to infection and surveillance of tumors. This article summarizes the current scientific evidence on the effects of supplementation with prebiotics, probiotics, and synbiotics on high-risk human papillomavirus (HPV) infections, precancerous lesions, and various stages of cervical cancer development and treatment while also examining the underlying molecular pathways involved. Our findings indicate that a higher dietary fiber intake is associated with a reduced risk of HPV infection, while certain probiotics have shown promising results in clearing HPV-related lesions. Additionally, certain strains of probiotics, prebiotics such as inulin and fructo-oligosaccharides, and synbiotics decrease the frequency of gastrointestinal adverse effects in cervical cancer patients. These agents attain their results by modulating crucial metabolic pathways, including the reduction of inflammation and oxidative stress, promoting apoptosis, inhibiting cell proliferation, and suppressing the activity of oncogenes, thus attenuating tumorigenesis. We conclude that although further human studies are necessary, robust evidence in preclinical models demonstrates that prebiotics, probiotics, and synbiotics play an essential role in cervical cancer, from infection to carcinogenesis and its medical treatment. Consequently, we strongly recommend conducting high-quality clinical trials using these agents as adjuvants since they have proven safe.
:::

::: callout-important
## [HPV vaccination improves immune response in children with respiratory papillomatosis](https://www.nature.com/articles/s41598-025-14787-2)

Prieto-Islas MA, Godoy-Dahbura E, Villalpando-Sánchez DC, Cortés-Benavides C, Hernández-Cuellar E, Castro-Eguiluz D, Alvarez-Neri H, Medina-Contreras O\
*Sci Rep* 15(1):29885\
doi 10.1038/s41598-025-14787-2, [PubMed](https://pubmed.ncbi.nlm.nih.gov/40813785/)

Recurrent respiratory papillomatosis (RRP) is a pathology characterized by the presence of neoplasm in the epithelium of the airways, where the larynx is the main affected organ. The cause of this disease is the low-risk Human Papillomavirus (HPV), where subtypes 6 and 11 are the most frequent. The only proven effective treatment is surgical resection of the lesions, and although there are adjunctive treatments to try to reduce the recurrence of neoplasms, it has not been proven that there is an effective alternative that achieves this effect. A proposal as adjuvant therapy is the HPV vaccine; although used in adults to treat the disease, the effect it has on immunological changes in a pediatric population with PRR has not been studied, so the objective of this work is to assess the efficacy of vaccination as an adjuvant treatment, by observing the immunological changes that are generated after vaccination, measuring the antibody titer as well as the cytokine profile present in the patients and relating it to the impact at the clinical in pediatric population. For this, blood samples and biopsies obtained by laryngeal surgery from 10 patients before and 6 months after completing the HPV vaccination scheme were compared. Viral load of the HPV6/11 serotypes was measured by qPCR, observing a decrease in copy number of both subtypes after vaccination. The antibody titer in the serum of the same patients was measured by ELISA, observing an increase in the amount of IgG antibodies without finding modifications in the IgM antibodies against HPV L1 protein. In addition, HPV vaccination was associated with a decrease in the immunosuppressive cytokine IL-10 in papilloma tissue and a significant increase in the pro-inflammatory cytokine TNFα in serum, suggesting a shift towards a Th1-mediated immune response. All these changes had an impact on the number of surgeries that were performed to remove the neoplasms, where there was a decrease in these during a six-month follow-up after vaccination. In conclusion, the vaccination as adjuvant therapy increased the number of IgG antibodies against the virus. It increased the amount of pro-inflammatory cytokines at the systemic level, reducing the viral load and the number of recurrences of papillomas.
:::

**Denisse Castro-Eguiluz** is a researcher for México at the [National Cancer Institute](https://www.incan.salud.gob.mx), where she works on cervical cancer. **Oscar Medina-Contreras** is a medical sciences researcher at [Mexico Children’s Hospital](https://www.himfg.edu.mx/), where he works on mucosal immunology.