---
title: "Publications"
---

<!--
::: {.callout-warning collapse="true"}
## upcoming
-   Crtam and IL-36$\gamma$ are required for the control of <i>Salmonella</i> infection in the intestine
:::
-->

::: {.callout-note collapse="true"}
## Sea cucumber (*Isostichopus badionotus*): bioactivity and wound healing capacity *in vitro* of small peptide isolates from digests of whole-body wall or purified collagen

Olivera-Castillo L, Grant G, Medina-Contreras O, Cruz-López H, Carrillo-Cocom L, Cruz-Córdova A, Segura-Cadiz F, Fernández-Velasco DA, Rodríguez-Morales S, Cauich-Rodríguez JV, Moo-Puc RE, Puerto-Castillo C, Moo-Pech GJ, Uuh-Narvaez JJ, Olvera-Novoa, MA, Rodriguez-Canul R\
[*Mar Drugs* 23(11), 411](https://www.mdpi.com/1660-3397/23/11/411)

Low-molecular-weight peptides derived from the digestion of body wall proteins in some sea cucumber species have wound-healing and health-promoting properties, but their potency varies widely by species, growth environment, age, and season. For the first time, small peptide (1–3 kDa) fractions have been isolated from the whole-body wall of the sea cucumber *Isostichopus badionotus* and its constituent collagen and tested for wound healing capacity *in vitro*. Ultrafiltered digests (1–3 kDa) of the pure collagen, as well as 1–3 kDa digests of the whole-body wall, had potent antioxidant activities and promoted rapid wound healing in a keratinocyte scratch wound assay. Gene expression studies suggested that the wound-healing actions of the individual collagen and body wall 1–3 kDa fractions differed significantly. Low-molecular-weight peptides derived from I. badionotus collagen did promote wound healing *in vitro*; however, their efficacy may have been modulated by additional factors produced during body wall or collagen digestion. These findings need to be confirmed *in vivo*.
:::

::: {.callout-note collapse="true"}
## The role of inflammasomes in LPS and Gram-negative bacterial sepsis

Hernández-Cuellar H, Tsuchiya K, Medina-Contreras O, Valle-Ríos R\
[*J Clin Med* 14(19), 7102](https://www.mdpi.com/2077-0383/14/19/7102)

**Background**: Sepsis is a life-threatening condition characterized by an uncontrolled immune response due to systemic infections. It is responsible for millions of deaths worldwide. Although inflammasomes play an important role in host defense, they have a detrimental role in sepsis induced by LPS or Gram-negative bacteria. We aimed to revise the molecular mechanisms of inflammasome activation in sepsis by LPS and Gram-negative bacteria other than cytokine release as treatments blocking TNF$\alpha$ and IL-1 cytokines have been ineffective even though cytokine storm is associated with lethality. **Results**: Studies with knockout mice deficient in inflammasome-derived cytokines have shown contrasting results on the role of these proinflammatory cytokines in the lethality of LPS- and Gram-negative-induced sepsis. However, DAMPs released after non-canonical inflammasome activation such as extracellular DNA, histones, HMGB1, and tissue factor result in disseminated-intravascular coagulation (DIC) and mortality in mice. Blocking these products in preclinical studies with animal models showed improved clinical scores and survival after LPS-induced sepsis or polymicrobial sepsis induced by Cecal Ligation and Puncture. **Conclusions**: Even though immunomodulatory drugs have shown inconclusive results as therapies for sepsis, blocking DAMPs associated with DIC may be considered for clinical trials in the future, especially in patients presenting biomarkers of coagulopathies.
:::

::: {.callout-note collapse="true"}
## HPV vaccination improves immune response in children with respiratory papillomatosis

Prieto-Islas MA, Godoy-Dahbura E, Villalpando-Sanchez DC,Cortés-Benavides C, Hernández-Cuellar E, Castro-Eguiluz Denisse, Álvarez-Neri H, Medina-Contreras O\
[*Sci Rep* 15, 29885](https://www.nature.com/articles/s41598-025-14787-2)

Recurrent respiratory papillomatosis (RRP) is a pathology characterized by the presence of neoplasm in the epithelium of the airways, where the larynx is the main affected organ. The cause of this disease is the low-risk Human Papillomavirus (HPV), where subtypes 6 and 11 are the most frequent. The only proven effective treatment is surgical resection of the lesions, and although there are adjunctive treatments to try to reduce the recurrence of neoplasms, it has not been proven that there is an effective alternative that achieves this effect. A proposal as adjuvant therapy is the HPV vaccine; although used in adults to treat the disease, the effect it has on immunological changes in a pediatric population with PRR has not been studied, so the objective of this work is to assess the efficacy of vaccination as an adjuvant treatment, by observing the immunological changes that are generated after vaccination, measuring the antibody titer as well as the cytokine profile present in the patients and relating it to the impact at the clinical in pediatric population. For this, blood samples and biopsies obtained by laryngeal surgery from 10 patients before and 6 months after completing the HPV vaccination scheme were compared. Viral load of the HPV6/11 serotypes was measured by qPCR, observing a decrease in copy number of both subtypes after vaccination. The antibody titer in the serum of the same patients was measured by ELISA, observing an increase in the amount of IgG antibodies without finding modifications in the IgM antibodies against HPV L1 protein. In addition, HPV vaccination was associated with a decrease in the immunosuppressive cytokine IL-10 in papilloma tissue and a significant increase in the pro-inflammatory cytokine TNFα in serum, suggesting a shift towards a Th1-mediated immune response. All these changes had an impact on the number of surgeries that were performed to remove the neoplasms, where there was a decrease in these during a six-month follow-up after vaccination. In conclusion, the vaccination as adjuvant therapy increased the number of IgG antibodies against the virus. It increased the amount of pro-inflammatory cytokines at the systemic level, reducing the viral load and the number of recurrences of papillomas.
:::

::: {.callout-note collapse="true"}
## Isthmin1 upregulation in the intestinal microenvironment during *Salmonella typhimurium* infection: identification and characterization of Isthmin1-producing cells

Gustavo Alberto Jaimes-Ortega GA, Angeles-Floriano T, Rivera-Torruco G, Almanza-Pérez JC, Xicohtencatl-Cortes J, Hernandez-Cuellar E, Medina-Contreras O, Cruz-Córdova A, Valle-Rios, Ricardo\
[*Microorganisms* 13(6), 1280](https://link.springer.com/article/10.1007/s00253-024-13380-3)

Isthmin1 (ISM1) is a constitutively secreted cytokine produced by barrier tissues and different immune cell types. Importantly, ISM1 is also expressed by cells with a hematopoietic stem cell phenotype in the lung and plays a role during hematopoiesis. Under inflammatory conditions, ISM1 levels are also altered. Given that the intestine is one of the tissues with the highest ISM1 gene expression, in this work, we characterized the immunophenotype of ISM1-producing cells in the small intestine of uninfected or *Salmonella typhimurium*-infected mice. We found a variety of ISM1^+^-expressing cells, including CD45+ cells, EpCAM+ cells, and, importantly, we also found different subsets of cells carrying hematopoietic stem cell markers (LSKs) expressing ISM1, and their frequency was perturbed during infection. Finally, we also found that isthmin1 is secreted into the intestinal lumen, and its concentration was increased during S. Typhimurium infection. Our findings suggest that increased luminal ISM1 secretion during mucosal infection may serve as a potential novel biomarker of pathogen-mediated inflammation.
:::

::: {.callout-note collapse="true"}
## Persistent stimulation of human mesenchymal stem/stromal cells with TNF$\alpha$ and IFN$\gamma$ affects the release of large extracellular vesicles with immunoregulatory phenotype

Castro-Manrreza M, Romano LE, López-García L, Medina-Contreras O, Montesinos J\
[*Stem Cells Dev* 34(13-14), 291-303](https://www.liebertpub.com/doi/10.1089/scd.2025.0064)

Mesenchymal stem/stromal cells (MSCs) possess immunoregulatory capacity, which is enhanced in an inflammatory environment. Participation of extracellular vesicles (EVs) in this function is proposed, as they can transport various immunoregulatory molecules. However, the impact of the inflammatory microenvironment on the load of the different types of EVs released by these cells is not fully known. Therefore, this work analyzes in detail the temporal effect of IFN$\gamma$, alone or in combination with TNF$\alpha$ (TNF$\alpha$ + IFN$\gamma$), on the cargo of immunoregulatory molecules (programmed cell death ligand 1 [PD-L1], CD73, and intercellular adhesion molecule 1 [ICAM-1]) in large extracellular vesicles (L-EVs) released by human bone marrow mesenchymal stem cells (BM-MSCs). The presence of these molecules on the surface of L-EVs was determined by flow cytometry. Our results demonstrate that exposing BM-MSCs to TNF$\alpha$ + IFN$\gamma$ for 24 h increases the percentage of PD-L1+ and CD73+ L-EVs. However, if this stimulus persists, the release of L-EVs with an immunoregulatory phenotype (PD-L1+, CD73+, and PD-L1+CD73+) decreases. The impact of pro-inflammatory cytokines on the transport of ICAM-1 by L-EVs is late, since up to 72 h of treatment with IFN$\gamma$ or TNF$\alpha$ + IFN$\gamma$, the percentage of ICAM-1+ L-EVs increases. In contrast, stimulation with IFN$\gamma$ for 72 h favors the release of CD73high and ICAM-1high L-EVs, but this effect also decreases in the presence of TNF$\alpha$. Our study generates novel knowledge about the impact of the inflammatory microenvironment on the cargo composition of L-EVs released by BM-MSCs and demonstrates, for the first time, that the prolonged presence of TNF$\alpha$ reduces the cargo of immunoregulatory molecules in these structures.
:::

::: {.callout-note collapse="true"}
## A Lambda-evo ($\lambda$evo) phage platform for Zika virus EDIII protein displayed

Negrete-Méndez H, Valencia-Toxqui G, Martínez-Peñafiel E, Medina-Contreras O, Fernández-Ramírez F, Morales-Ríos E, Navarro-González LJ, Torres-Flores JM, Kameyama L\
[*Appl Microbiol Biotechnol* 109(8), 1–20](https://link.springer.com/article/10.1007/s00253-024-13380-3)

One of the most significant bacteriophage technologies is phage display, in which heterologous peptides are exhibited on the virion surface. This work describes the display of λ decorative protein Dλ linked to the E protein domain III of Zika virus (Dλ-ZEDIII), to the GFP protein (Dλ-GFP), or to different domain III epitopes of the EZIKV protein (Dλ-TD), exhibited on the surface of an in vitro evolved lambda phage (λevo). This phage harbors a gene D deletion and was subjected to directed evolution using Escherichia coli W3110/pDλ-ZEDIII as background. After 20 days (20 cycles of dilution), the λevo phage developed a ~ 22% genome deletion affecting the non-essential λ b region, rendering a more stable phage that exhibited fusion proteins Dλ-ZEDIII or Dλ-GFP but not Dλ-TD. Despite the λevo system was able to decorate itself with the Dλ-ZEDIII protein, the production of viral particles was ~ 1000-fold lower than the λ wild-type, due to the unexpected Dλ-ZEDIII protein aggregation into bacterial inclusion bodies. Decorated phages (10^6^ PFU (plaque forming units)/100 µl) were inoculated into BALB/c mice, and subsequent dot blot and Western blot immunoassays proved the production of murine antibodies against ZIKV (Zika virus). This multipurpose λevo phage display platform may be used interchangeably with other more soluble peptides, providing better yields.
:::

::: {.callout-note collapse="true"}
## Editorial: Cervical cancer: updates from the Mexican national consensus

Cetina-Pérez L, Medina-Contreras O\ 
[*Front Oncol* 14:1493334](https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2024.1493334/full)
:::

::: {.callout-note collapse="true"}
## UNAM-HIMFG bacterial lysate activates the immune response and inhibits colonization of bladder of Balb/c mice infected with the uropathogenic CFT073 *Escherichia coli* strain

Acevedo-Monroy SE, Hernández-Chiñas U, Medina-Contreras O, López-Díaz O, Ahumada-Cota RE, Martínez-Gómez D, Huerta-Yepez S, Tirado-Rodríguez AB, Molina-López J, Castro-Luna R, Martínez-Cristóbal L, Rojas-Castro FE, Chávez-Berrocal ME, Verdugo-Rodríguez A, Eslava-Campos CA\ 
[*Int J Mol Sci* 25(18):9876](https://www.mdpi.com/1422-0067/25/18/9876)

Urinary tract infections (UTIs) represent a clinical and epidemiological problem of worldwide impact that affects the economy and the emotional state of the patient. Control of the condition is complicated due to multidrug resistance of pathogens associated with the disease. Considering the difficulty in carrying out effective treatment with antimicrobials, it is necessary to propose alternatives that improve the clinical status of the patients. With this purpose, in a previous study, the safety and immunostimulant capacity of a polyvalent lysate designated UNAM-HIMFG prepared with different bacteria isolated during a prospective study of chronic urinary tract infection (CUTI) was evaluated. In this work, using an animal model, results are presented on the immunostimulant and protective activity of the polyvalent UNAM-HIMFG lysate to define its potential use in the control and treatment of CUTI. Female Balb/c mice were infected through the urethra with Escherichia coli CFT073 (UPEC O6:K2:H1) strain; urine samples were collected before the infection and every week for up to 60 days. Once the animals were colonized, sublingual doses of UNAM-HIMFG lysate were administrated. The colonization of the bladder and kidneys was evaluated by culture, and their alterations were assessed using histopathological analysis. On the other hand, the immunostimulant activity of the compound was analyzed by qPCR of spleen mRNA. Uninfected animals receiving UNAM-HIMFG lysate and infected animals administered with the physiological saline solution were used as controls. During this study, the clinical status and evolution of the animals were evaluated. At ninety-six hours after infection, the presence of CFT073 was identified in the urine of infected animals, and then, sublingual administration of UNAM-HIMFG lysate was started every week for 60 days. The urine culture of mice treated with UNAM-HIMFG lysate showed the presence of bacteria for three weeks post-treatment; in contrast, in the untreated animals, positive cultures were observed until the 60th day of this study. The histological analysis of bladder samples from untreated animals showed the presence of chronic inflammation and bacteria in the submucosa, while tissues from mice treated with UNAM-HIMFG lysate did not show alterations. The same analysis of kidney samples of the two groups (treated and untreated) did not present alterations. Immunostimulant activity assays of UNAM-HIMFG lysate showed overexpression of TNF-α and IL-10. Results suggest that the lysate activates the expression of cytokines that inhibit the growth of inoculated bacteria and control the inflammation responsible for tissue damage. In conclusion, UNAM-HIMFG lysate is effective for the treatment and control of CUTIs without the use of antimicrobials.
:::

::: {.callout-note collapse="true"}
## Tumor suppressive cross linking of anti-*T. cruzi* antibodies in acute lymphoblastic leukemia

Maravelez Acosta VA, Crisóstomo Vázquez MP, Eligio García L, Franco Sandoval LO, Castro Pérez D, Patiño López G, Medina Contreras O, Jiménez Cardoso E\
[*Int J Mol Sci* 25(15):8307](https://www.mdpi.com/1422-0067/25/15/8307)

Parasites have been associated with possible anticancer activity, including Trypanosoma cruzi, which has been linked to inhibiting the growth of solid tumors. To better understand this antitumor effect, we investigated the association of anti-T. cruzi antibodies with B cells of the acute lymphoblastic leukemia (ALL) SUPB15 cell line. The antibodies were generated in rabbits. IgGs were purified by affinity chromatography. Two procedures (flow cytometry (CF) and Western blot(WB)) were employed to recognize anti-T. cruzi antibodies on SUPB15 cells. We also used CF to determine whether the anti-T. cruzi antibodies could suppress SUPB15 cells. The anti-T. cruzi antibodies recognized 35.5% of the surface antigens of SUPB15. The complement-dependent cytotoxicity (CDC) results demonstrate the cross-suppression of anti-T. cruzi antibodies on up to 8.4% of SUPB15 cells. For the WB analysis, a band at 100 kDa with high intensity was sequenced using mass spectrometry, identifying the protein as nucleolin. This protein may play a role in the antitumor effect on T. cruzi. The anti-T. cruzi antibodies represent promising polyclonal antibodies that have the effect of tumor-suppressive cross-linking on cancer cells, which should be further investigated.
:::

::: {.callout-note collapse="true"}
## IFN$\gamma$ stimulates Paneth cell secretion through necroptosis mTORC1 dependent

Encarnacion-Garcia MR, De la Torre-Baez R, Hernandez-Cueto MA, Velázquez-Villegas LA, Candelario-Martinez A, Sánchez-Argáez AB, Horta-López PH, Montoya-García A, Jaimes-Ortega GA, Lopez-Bailon L, Piedra-Quintero Z, Carrasco-Torres G, De Ita M, Figueroa-Corona MP, Muñoz-Medina JE, Sánchez-Uribe M, Ortiz-Fernández A, Meraz-Ríos MA, Silva-Olivares A, Betanzos A, Baay-Guzman GJ, Navarro-Garcia F, Villa-Treviño S, Garcia-Sierra F, Cisneros B, Schnoor M, Ortíz-Navarrete VF, Villegas-Sepúlveda N, Valle-Rios R, Medina-Contreras O, Noriega LG, Nava P\
[*Eur J Immunol* 54: 2350716](https://onlinelibrary.wiley.com/doi/10.1002/eji.202350716)

Immune mediators affect multiple biological functions of intestinal epithelial cells (IECs) and, like Paneth and Paneth-like cells, play an important role in intestinal epithelial homeostasis. IFN-$\gamma$ a prototypical proinflammatory cytokine disrupts intestinal epithelial homeostasis. However, the mechanism underlying the process remains unknown. In this study, using in vivo and in vitro models we demonstrate that IFN-$\gamma$ is spontaneously secreted in the small intestine. Furthermore, we observed that this cytokine stimulates mitochondrial activity, ROS production, and Paneth and Paneth-like cell secretion. Paneth and Paneth-like secretion downstream of IFN-$\gamma$, as identified here, is mTORC1 and necroptosis-dependent. Thus, our findings revealed that the pleiotropic function of IFN-$\gamma$ also includes the regulation of Paneth cell function in the homeostatic gut.
:::

::: {.callout-note collapse="true"}
## Effects of prebiotics, probiotics, and synbiotics on the prevention and treatment of cervical cancer: Mexican consensus and recommendations

Gutiérrez Salmeán G, Delgadillo González M, Rueda Escalona AA, Leyva Islas JA, Castro-Eguiluz D\ 
[*Front Oncol* 14:1383258](https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2024.1383258/full)

Gut microbiota plays a crucial role in modulating immune responses, including effector response to infection and surveillance of tumors. This article summarizes the current scientific evidence on the effects of supplementation with prebiotics, probiotics, and synbiotics on high-risk human papillomavirus (HPV) infections, precancerous lesions, and various stages of cervical cancer development and treatment while also examining the underlying molecular pathways involved. Our findings indicate that a higher dietary fiber intake is associated with a reduced risk of HPV infection, while certain probiotics have shown promising results in clearing HPV-related lesions. Additionally, certain strains of probiotics, prebiotics such as inulin and fructo-oligosaccharides, and synbiotics decrease the frequency of gastrointestinal adverse effects in cervical cancer patients. These agents attain their results by modulating crucial metabolic pathways, including the reduction of inflammation and oxidative stress, promoting apoptosis, inhibiting cell proliferation, and suppressing the activity of oncogenes, thus attenuating tumorigenesis. We conclude that although further human studies are necessary, robust evidence in preclinical models demonstrates that prebiotics, probiotics, and synbiotics play an essential role in cervical cancer, from infection to carcinogenesis and its medical treatment. Consequently, we strongly recommend conducting high-quality clinical trials using these agents as adjuvants since they have proven safe.
:::

::: {.callout-note collapse="true"}
## Polyvalent bacterial lysate with potential use to treatment and 2 control of recurrent urinary tract infections

Acevedo-Monroy SE, Rocha-Ramírez L, Martinez-Gomez D, Basurto-Alcantara FJ, Medina-Contreras O, Hernández-Chiñas U, Quiñones-Peña MA, García-Sosa D, Ramírez-Lezama J, Rodríguez-García J, González-Villalobos E, Castro-Luna R, Martínez-Cristóbal L, Eslava-Campos CA\
[*Int J Mol Sci* 25(11):6157](https://www.mdpi.com/1422-0067/25/11/6157)

Overuse of antimicrobials has greatly contributed to the increase in the emergence of multidrug-resistant bacteria, a situation that hinders the control and treatment of infectious diseases. This is the case with urinary tract infections (UTIs), which represent a substantial percentage of worldwide public health problems, thus the need to look for alternatives for their control and treatment. Previous studies have shown the usefulness of autologous bacterial lysates as an alternative for the treatment and control of UTIs. However, a limitation is the high cost of producing individual immunogens. At the same time, an important aspect of vaccines is their immunogenic amplitude, which is the reason why they must be constituted of diverse antigenic components. In the case of UTIs, the etiology of the disease is associated with different bacteria, and even Escherichia coli, the main causal agent of the disease, is made up of several antigenic variants. In this work, we present results on the study of a bacterial lysate composed of 10 serotypes of *Escherichia coli* and by *Klebsiella pneumoniae*, *Klebsiella aerogenes*, *Enterococcus faecalis*, *Proteus mirabilis*, *Citrobacter freundii*, and *Staphylococcus haemolyticus*. The safety of the compound was tested on cells in culture and in an animal model, and its immunogenic capacity by analysing in vitro human and murine macrophages (cell line J774 A1). The results show that the polyvalent lysate did not cause damage to the cells in culture or alterations in the animal model used. The immunostimulatory activity assay showed that it activates the secretion of TNF-α and IL-6 in human macrophages and TNF-α in murine cells. The obtained results suggest that the polyvalent lysate evaluated can be an alternative for the treatment and control of chronic urinary tract infections, which will reduce the use of antimicrobials.
:::

::: {.callout-note collapse="true"}
## Screening of Leptin-LepR modulators using molecular docking and binding assay

Jiménez-Pineda A, Vique-Sánchez JL, Medina-Contreras O, Benitez-Cardoza CG
\[*Bioinformation* 20(5), 404-411](https://www.bioinformation.net/020/973206300200404.htm)

Leptin is a pleiotropic hormone which, upon binding to its cognate leptin receptor (LepR), induces the activation of the JAK2/ERK, /STAT3, /STAT5 and IRS/PI3 kinase signaling cascades. Hence, we used molecular docking and a chemical library to identify 18 compounds with high probability of interacting with the leptin binding domain (LBD) of LepR. 6 out of 18 compounds were selected based on toxicological and physicochemical properties to evaluate their effect in the formation of Leptin-LepR complex using ELISA assays. The six compounds showed discreet but significant modulation on the complex formation. These results have important implications in proposing novel strategies for modulating the formation of the Leptin-LepR complex, as therapeutic alternatives for patho-physiologies where the formation of this complex is deregulated.
:::

::: {.callout-note collapse="true"}
## Molecular aspects of cervical cancer: a pathogenesis update

Vallejo-Ruiz V, Gutiérrez-Xicoténcatl ML, Medina-Contreras O, Lizano-Soberón M\
[*Front Oncol* 14, 1356581](https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2024.1356581/full)

Cervical cancer (CC) is a significant health problem, especially in low-income countries. Functional studies on the human papillomavirus have generated essential advances in the knowledge of CC. However, many unanswered questions remain. This mini-review discusses the latest results on CC pathogenesis, HPV oncogenesis, and molecular changes identified through next-generation technologies. Interestingly, the percentage of samples with HPV genome integrations correlates with the degree of the cervical lesions, suggesting a role in the development of CC. Also, new functions have been described for the viral oncoproteins E5, E6, and E7, resulting in the acquisition and maintenance of cancer hallmarks, including proliferation, immune response evasion, apoptosis, and genomic instability. Remarkably, E5 oncoprotein affects signaling pathways involved in the expression of interferon-induced genes and EGFR-induced proliferation, while E6 and E7 oncoproteins regulate the DNA damage repair and cell cycle continuity pathways. Furthermore, next-generation technologies provide vast amounts of information, increasing our knowledge of changes in the genome, transcriptome, proteome, metabolome, and epigenome in CC. These studies have identified novel molecular traits associated with disease susceptibility, degree of progression, treatment response, and survival as potential biomarkers and therapeutic targets.
:::

::: {.callout-note collapse="true"}
## Differences in biofilm formation by methicillin-resistant and methicillin-susceptible *Staphylococcus aureus* strains

Hernández-Cuellar E, Tsuchiya K, Valle-Ríos R, Medina-Contreras O [*Diseases* 11(4), 160](https://www.mdpi.com/2079-9721/11/4/160)

*Staphylococcus aureus* (S. aureus) is a common pathogen involved in community- and hospital-acquired infections. Its biofilm formation ability predisposes it to device-related infections. Methicillin-resistant *S. aureus* (MRSA) strains are associated with more serious infections and higher mortality rates and are more complex in terms of antibiotic resistance. It is still controversial whether MRSA are indeed more virulent than methicillin-susceptible *S. aureus* (MSSA) strains. A difference in biofilm formation by both types of bacteria has been suggested, but how only the presence of the SCCmec cassette or mecA influences this phenotype remains unclear. In this review, we have searched for literature studying the difference in biofilm formation by MRSA and MSSA. We highlighted the relevance of the icaADBC operon in the PIA-dependent biofilms generated by MSSA under osmotic stress conditions, and the role of extracellular DNA and surface proteins in the PIA-independent biofilms generated by MRSA. We described the prominent role of surface proteins with the LPXTG motif and hydrolases for the release of extracellular DNA in the MRSA biofilm formation. Finally, we explained the main regulatory systems in *S. aureus* involved in virulence and biofilm formation, such as the SarA and Agr systems. As most of the studies were in vitro using inert surfaces, it will be necessary in the future to focus on biofilm formation on extracellular matrix components and its relevance in the pathogenesis of infection by both types of strains using *in vivo* animal models.
:::

::: {.callout-note collapse="true"}
## Chemoradiotherapy treatment with gemcitabine improves renal function in locally advanced cervical cancer patients with renal dysfunction

Alarcón-Barrios S, Luvián-Morales J, Castro-Eguiluz D, Delgadillo-González M, Lezcano-Velázquez BO, Arango-Bravo EA, Flores-Cisneros L, Aguiar Rosas S, Cetina-Pérez L\
*Curr Probl Cancer* 48, 101041
:::

::: {.callout-note collapse="true"}
## Validation of the QLQ-CAX24 instrument in cervical cancer and its association with cachexia classifications

Luvián-Morales J, Castillo-Aguilar J, Delgadillo-González M, Cisneros-Sánchez A, Bosch-Gutiérrez J, Castro-Eguiluz D, Cetina-Pérez L, Oñate-Ocaña LF\
[*Jpn J Clin Oncol* 53(4), 304-312](https://academic.oup.com/jjco/article/53/4/304/6964664)

Cancer-related cachexia (CRC) is a common phenomenon in cervical cancer (CC), severely affecting clinical response, drug toxicity and survival. The patients' point of view should be evaluated to quantify the impact of CRC, and adequate instruments to do so are required. Thus, the study aimed to validate the Mexican-Spanish version of the QLQ-CAX24 instrument in women with CC. A cohort of women with CC answered the EORTC QLQ-C30 and QLQ-CAX24 instruments. The psychometric and clinimetric properties of the instruments were assessed. Two hundred and forty-four women were included; the mean age was 50 years (IQR: 41-60) and 188 (77%) were first diagnosed in locally advanced stages. The QLQ-CAX24 internal consistency test demonstrated adequate convergent (Spearman correlation coefficient 0.08-0.709) and divergent validity (Spearman correlation coefficient 0.006-0.471). Cronbach's alpha coefficients of the three multi-item scales were \>0.5 (minimum 0.539, maximum 0.84). Patients with decreased handgrip strength, low fat-free mass, or high C-reactive protein levels had worse QLQ-CAX24 scale scores. Cachexia was diagnosed with the SCRINIO, Fearon and Evans criteria, and 31.5, 32.4 and 38.5% of women had cachexia, respectively. Patients with cachexia had the worst scores in terms of quality of life. The test re-test analysis did not show differences between visits in patients without malnutrition. The Mexican-Spanish version of the QLQ-CAX24 instrument is reliable and valid. Low handgrip strength, low fat-free mass and high C-reactive protein levels were associated with poor scale scores.
:::

::: {.callout-note collapse="true"}
## The health system and access to treatment in patients with cervical cancer in Mexico

Arango-Bravo EA, Cetina-Pérez LDC, Galicia-Carmona T, Castro-Eguiluz D, Gallardo-Rincón D, Cruz-Bautista I, Dueñas-Gonzalez A\
*Front Oncol* 12, 1028291
:::

::: {.callout-note collapse="true"}
## Clinical benefits of olaparib in Mexican ovarian cancer patients with founder mutation BRCA1-Del ex9-12

Gallardo-Rincón D, Montes-Servín E, Alamilla-García G, Montes-Servín E, Bahena-González A, Cetina-Pérez L, Morales Vásquez F, Cano-Blanco C, Coronel-Martínez J, González-Ibarra E, Espinosa-Romero R, María Alvarez-Gómez R, Pedroza-Torres A, Castro-Eguiluz D\
*Front Genet* 13, 863956
:::

::: {.callout-note collapse="true"}
## Impact of metabolic syndrome on the risk of endometrial cancer and the role of lifestyle in prevention

Pérez-Martín AR, Castro-Eguiluz D, Cetina-Pérez L, Velasco-Torres Y, Bahena-González A, Montes-Servín E, González-Ibarra E, Espinosa-Romero R, Gallardo-Rincón D\
*Bosn J Basic Med Sci* 22(4):499-510
:::

::: {.callout-note collapse="true"}
## Treatment of locally advanced cervical cancer with kidney failure and comorbidities

Arango Bravo E, Carmona T, Castro-Eguiluz D, Gallardo-Rincón D, Flores E, Cetina-Pérez LDC *Oncology* 35(11), 741-745
:::

::: {.callout-note collapse="true"}
## Effectiveness of concomitant chemoradiotherapy with gemcitabine in locally advanced cervical cancer patients with comorbidities

Brau-Figueroa H, Arango-Bravo E, Castro-Eguiluz D, Galicia-Carmona T, Lugo-Alferez LA, Cruz-Bautista I, Jiménez-Lima R, Cetina-Pérez L\
*Cancer Res Treat* 54(2), 554-562
:::

::: {.callout-note collapse="true"}
## Validation of the QLQ-CX24 questionnaire for the assessment of quality of life in Mexican women with cervical cancer

Luvián-Morales J, Flores-Cisneros L, Jiménez-Lima R, Alarcón-Barrios S, Salazar-Mendoza J, Castro-Eguiluz D, Cetina-Pérez L, Oñate-Ocaña LF\
*Int J Gynecol Cancer* 31(9), 1228-1235
:::

::: {.callout-note collapse="true"}
## ADXS11-001 LM-LLO as specific immunotherapy in cervical cancer

Galicia-Carmona T, Arango-Bravo E, Serrano-Olvera JA, Flores-de La Torre C, Cruz-Esquivel I, Villalobos-Valencia R, Morán-Mendoza A, Castro-Eguiluz D, Cetina-Pérez L\
*Hum Vaccin Immunother* 17(8), 2617-2625
:::

::: {.callout-note collapse="true"}
## Functional foods modulating inflammation and metabolism in chronic diseases: a systematic review

Luvián-Morales J, Varela-Castillo FO, Flores-Cisneros L, Cetina-Pérez L, Castro-Eguiluz D\
[*Crit Rev Food Sci Nutr* 62(16), 4371-4392](https://www.tandfonline.com/doi/abs/10.1080/10408398.2021.1875189)

Chronic diseases are responsible for approximately 71% global deaths. These are characterized by chronic low-grade inflammation and metabolic alterations. "Functional foods" have been attributed with anti-inflammatory properties, demonstrated in cell lines and murine models; however, studies in humans are inconclusive. The purpose of this systematic review is to identify clinical trials that analyzed changes in inflammatory and metabolic mediators, in response to consumption of specific functional foods. A total of 3581 trials were screened and 88 were included for this review. Foods identified to regulate inflammation included cranberries, grapes, pomegranate, strawberries, wheat, whole grain products, low fat dairy products, yogurt, green tea, cardamom, turmeric, soy foods, almonds, chia seeds, flaxseed, pistachios, algae oil, flaxseed oil and grape seed oil. Clinical trials that focus on a dietary pattern rich in functional foods are necessary to explore if the additive effect of these foods lead to more clinically relevant outcomes.
:::

::: {.callout-note collapse="true"}
## Therapeutic use of human papillomavirus vaccines in cervical lesions

Castro-Eguiluz D, Barquet-Muñoz SA, Arteaga-Gómez AC, Salcedo Hernández RA, Rodríguez-Trejo A, Gallardo-Rincón D, Serrano-Olvera JA, Aranda-Flores C\
*Rev Invest Clin* 72(4), 239-249
:::

::: {.callout-note collapse="true"}
## A trabecular micro-bypass stent combined with phacoemulsification efficiently reduces intraocular pressure in open angle glaucoma in Mexican population

Escamilla-Gallegos SI, Ochoa-Araujo DA, Domínguez-Hernández E, De La Torre-Tovar JD, Valencia-Rojas G, Esparza-Rocha G, Urzua-De La Luz P, Castellanos-Castellanos YA, Vázquez-Ramirez A, Ruiz-Magaña F, Padilla-Baca F, Ruiz-Peralta K, Medina-Contreras O\
[*EC Ophthalmology* 14(10), 1-8](https://ecronicon.net/ecop/a-trabecular-micro-bypass-stent-combined-with-phacoemulsification-efficiently-reduces-intraocular-pressure-in-primary-open-angle-glaucoma-in-mexican-population)

Purpose: The aim of this trial was to evaluate the safety and efficacy of a trabecular micro-bypass stent iStent combined with phacoemulsification in subjects with mild to moderate primary open angle glaucoma. Methods: A prospective, randomized, open, controlled, clinical trial was performed an Mexico’s Central Militar Hospital. The intervention was the implantation of a trabecular micro-bypass stent (iStent) combined with cataract surgery. 23 patients whom met the inclusion criteria were recruited into the trial. Intraocular pressure, best corrected visual acuity, visual field functional study, and the use of hypotensive drugs was documented and the patients were divided into two random groups, one underwent cataract surgery and the other underwent cataract surgery plus a trabecular microbypass stent (iStent) implantation. Results: There was a reduction of up to 75% in the use of topical hypotensive drugs after one year iStent implantation. Conclusion: The use of the iStent combined with phacoemulsification results in a sustained hypotensive effect in Mexican patients diagnosed with primary open angle glaucoma.
:::

::: {.callout-note collapse="true"}
## Editorial: Women in mucosal immunity\

Bose T, Medina-Contreras O, Fernández C, Finotto S\
[*Front Immunol* 14, 1282709](https://www.frontiersin.org/articles/10.3389/fimmu.2023.1282709/full)

Environmental triggers may profoundly affect host immune responses thereby causing structural alterations and tissue damage. However, the mechanisms by which persistent environmental triggers at local mucosal interfaces deregulate immunity are poorly understood.
:::

::: {.callout-note collapse="true"}
## Rapid and efficient enrichment of mouse spinal cord microglia

Gutiérrez-Román CI, Meléndez-Camargo ME, García-Rojas CC, Jiménez-Olvera M, Gutierrez-Román SH, Medina-Contreras O\
[*J Vis Exp* 199, e65961](https://www.jove.com/es/t/65961/rapid-and-efficient-enrichment-of-mouse-spinal-cord-microglia)

The vertebral column defines a vertebrate and shapes the spinal canal, a cavity that encloses and safeguards the spinal cord. Proper development and function of the mammalian central nervous system rely significantly on the activity of resident macrophages known as microglia. Microglia display heterogeneity and multifunctionality, enabling distinct gene expression and behavior within the spinal cord and brain. Numerous studies have explored cerebral microglia function, detailing purification methods extensively. However, the purification of microglia from the spinal cord in mice lacks a comprehensive description. In contrast, the utilization of a highly purified collagenase, as opposed to an unrefined extract, lacks reporting within central nervous system tissues. In this study, the vertebral column and spinal cord were excised from 8-10 week-old C57BL/6 mice. Subsequent digestion employed a highly purified collagenase, and microglia purification utilized a density gradient. Cells underwent staining for flow cytometry, assessing viability and purity through CD11b and CD45 staining. Results yielded an average viability of 80% and a mean purity of 95%. In conclusion, manipulation of mouse microglia involved digestion with a highly purified collagenase, followed by a density gradient. This approach effectively produced substantial spinal cord microglia populations.
:::

::: {.callout-note collapse="true"}
## T cell functions and organ infiltration by leukemic T cells require cortactin

Castellanos-Martínez R, León-Vega II, Guerrero-Fonseca IM, Vargas-Robles H, Jiménez-Camacho KE, Hernández-Galicia G, Ortiz-Navarrete VF, Rottner K, Medina-Contreras O, Schnoor M\
[*J Leukoc Biol* 113(3), 315-25](https://academic.oup.com/jleukbio/article/113/3/315/6992623?login=false/)

T cell acute lymphoblastic leukemia (T-ALL) is an aggressive hematological malignancy that is still fatal in many cases. T cell blasts are characterized by hyperactivation and strong proliferative and migratory capacities. The chemokine receptor CXCR4 is involved in mediating malignant T cell properties, and cortactin has been shown to control CXCR4 surface localization in T-ALL cells. We have previously shown that cortactin overexpression is correlated with organ infiltration and relapse in B-ALL. However, the role of cortactin in T cell biology and T-ALL remains elusive. Here, we analyzed the functional relevance of cortactin for T cell activation and migration and the implications for T-ALL development. We found that cortactin is upregulated in response to T cell receptor engagement and recruited to the immune synapse in normal T cells. Loss of cortactin caused reduced IL-2 production and proliferation. Cortactin-depleted T cells showed defects in immune synapse formation and migrated less due to impaired actin polymerization in response to T cell receptor and CXCR4 stimulation. Leukemic T cells expressed much higher levels of cortactin compared to normal T cells that correlated with greater migratory capacity. Xenotransplantation assays in NSG mice revealed that cortactin-depleted human leukemic T cells colonized the bone marrow significantly less and failed to infiltrate the central nervous system, suggesting that cortactin overexpression drives organ infiltration, which is a major complication of T-ALL relapse. Thus, cortactin could serve as a potential therapeutic target for T-ALL and other pathologies involving aberrant T cell responses.
:::

::: {.callout-note collapse="true"}
## Leukocyte surface expression of the endoplasmic reticulum chaperone GRP78 is increased in severe COVID-19

Angeles-Floriano T, San Juan-Méndez A, Rivera-Torruco G, Parra-Ortega I, Lopez-Martinez B, Martinez-Castro J, Marin-Santiago S, Alcántara-Hernández C, Martínez-Martínez A, Márquez-González H, Klünder-Klünder M, Olivar-López V, Zaragoza-Ojeda M, Arenas-Huertero F, Torres-Aguilar H, Medina-Contreras O, Zlotnik A, Valle-Rios R\
[*J Leukoc Biol* 113(1), 1-10](https://academic.oup.com/jleukbio/article/113/1/1/6979766/)

Hyperinflammation present in individuals with severe COVID-19 has been associated with an exacerbated cytokine production and hyperactivated immune cells. Endoplasmic reticulum stress leading to the unfolded protein response has been recently reported as an active player in inducing inflammatory responses. Once unfolded protein response is activated, GRP78, an endoplasmic reticulum-resident chaperone, is translocated to the cell surface (sGRP78), where it is considered a cell stress marker; however, its presence has not been evaluated in immune cells during disease. Here we assessed the presence of sGRP78 on different cell subsets in blood samples from severe or convalescent COVID-19 patients. The frequency of CD45^+^sGRP78^+^ cells was higher in patients with the disease compared to convalescent patients. The latter showed similar frequencies to healthy controls. In patients with COVID-19, the lymphoid compartment showed the highest presence of sGRP78+ cells versus the myeloid compartment. CCL2, TNF$\alpha$, C-reactive protein, and international normalized ratio measurements showed a positive correlation with the frequency of CD45^+^sGRP78^+^ cells. Finally, gene expression microarray data showed that activated T and B cells increased the expression of GRP78, and peripheral blood mononuclear cells from healthy donors acquired sGRP78 upon activation with ionomycin and PMA. Thus, our data highlight the association of sGRP78 on immune cells in patients with severe COVID-19.
:::

::: {.callout-note collapse="true"}
## Immunoproteomics of cow's milk allergy in Mexican pediatric patients

Torres-Arroyo A, Martínez-Aguilar J, Castillo-Villanueva A, Zárate-Mondragón F, Cervantes-Bustamante R, Patiño-López G, Medina-Contreras O, Espinosa-Padilla SE, Valencia-Rojas S, Romero-Guzmán L, Oria-Hernández J, Reyes-Vivas H\
[*J Proteomics* 273, 104809](https://www.sciencedirect.com/science/article/abs/pii/S1874391922003335)

Immunological mechanisms of non-IgE-mediated cow's milk protein allergy (CMPA) are not well understood. Such a circumstance requires attention with the aim of discovering new biomarkers that could lead to better diagnostic assays for early treatment. Here, we sought both to investigate the mechanism that underlies non-IgE-mediated CMPA and to identify cow's milk immunoreactive proteins in a Mexican pediatric patient group (n = 34). Hence, we determined the IgE and IgG1-4 subclass antibody levels against cow's milk proteins (CMP) by ELISA. Then, we performed 2D-Immunoblots using as first antibody immunoglobulins in the patients'serum that bound specifically against CMP together with CMP enrichment by ion-exchange chromatography. Immunoreactive proteins were identified by mass spectrometry-based proteomics. The serological test confirmed absence of specific IgE in the CMPA patients but showed significant increase in antigen-specific IgG1. Additionally, we identified 11 proteins that specifically bound to IgG1. We conclude that the detection of specific IgG1 together with an immunoproteomics approach is highly relevant to the understanding of CMPA's physiopathology and as a possible aid in making a prognosis since current evidence indicates IgG1 occurrence as an early signal of potential risk toward development of IgE-mediated food allergy. SIGNIFICANCE: Allergies are one of the most studied topics in the field of public health and novel protein allergens are found each year. Discovery of new principal and regional allergens has remarkable repercussions in precise molecular diagnostics, prognostics, and more specific immunotherapies. In this context, specific IgE is widely known to mediate physiopathology; however, allergies whose mechanism does not involve this immunoglobulin are poorly understood although their incidence has increased. Therefore, accurate diagnosis and adequate treatment are delayed with significant consequences on the health of pediatric patients. The study of type and subtypes of immunoglobulins associated with the immunoreactivity of cow's milk proteins together with an immunoproteomics approach allows better comprehension of physiopathology, brings the opportunity to discover new potential cow's milk protein allergens and may help in prognosis prediction (IgG1 occurrence as an early signal of possible risk toward development of IgE-mediated food allergy).
:::

::: {.callout-note collapse="true"}
## IL-36$\gamma$ is secreted through an unconventional pathway using the Gasdermin D and P2X7R membrane pores

Manzanares-Meza LD, Gutiérrez-Román CI, Jiménez-Pineda A, Castro-Martínez F, Patiño-López G, Rodríguez-Arellano E, Valle-Rios R, Ortíz-Navarrete VF, Medina-Contreras O\
[*Front Immunol* 13, 979749](https://www.frontiersin.org/articles/10.3389/fimmu.2022.979749/full)

Mucosal innate immunity functions as the first line of defense against invading pathogens. Members of the IL-1 family are key cytokines upregulated in the inflamed mucosa. Inflammatory cytokines are regulated by limiting their function and availability through their activation and secretion mechanisms. IL-1 cytokines secretion is affected by the lack of a signal peptide on their sequence, which prevents them from accessing the conventional protein secretion pathway; thus, they use unconventional protein secretion pathways. Here we show in mouse macrophages that LPS/ATP stimulation induces cytokine relocalization to the plasma membrane, and conventional secretion blockade using monensin or Brefeldin A triggers no IL-36$\gamma$ accumulation within the cell. *In silico* modeling indicates IL-36$\gamma$ can pass through both the P2X7R and Gasdermin D pores, and both IL-36$\gamma$, P2X7R and Gasdermin D mRNA are upregulated in inflammation; further, experimental blockade of these receptors' limits IL-36$\gamma$ release. Our results demonstrate that IL-36$\gamma$ is secreted mainly by an unconventional pathway through membrane pores formed by P2X7R and Gasdermin D.
:::

::: {.callout-note collapse="true"}
## Differentially expressed proteins in platelets derived from patients with hypertension

Armenta-Medina Y, Martínez-Vieyra I, Medina-Contreras O, Benitez-Cardoza CG, Jiménez-Pineda A, Reyes-López CA, Cerecedo D\
[*J Hum Hypertens* 36(7), 640-50](https://www.nature.com/articles/s41371-021-00555-y)

Hypertension (HTN) causes end-organ damage and is a major cause of morbidity and mortality globally. Recent studies suggested blood cells participate in the maintenance of HTN. Platelets-anucleated cell fragments derived from megakaryocytes-exert diverse functions, including their well-characterized role in the formation of hemostatic clots. However, platelets from patients with HTN exhibit altered membrane lipid and protein compositions that impact platelet function and lead to formation of aggregates and vascular obstructions. Here, for the first time, we have identified, by proteomic analyses, the most relevant 11 proteins that show the greatest difference in their expression in platelets derived from patients with HTN, in comparison with those from normotensive individuals. These proteins are involved in cytoskeletal organization and the coagulation cascade that contributes to platelet activation, release of granule contents, and aggregation, which culminate in thrombus formation. These results have important implications in our understanding of the molecular mechanisms associated with the development of HTN, and in consequence, the development of new strategies to counteract the cardiovascular disorders associated with constitutive activation of platelets in HTN.
:::

::: {.callout-note collapse="true"}
## An extremely low-frequency vortex magnetic field modifies protein expression, rearranges the cytoskeleton, and induces apoptosis of a human neuroblastoma cell line

Aparicio-Bautista DI, Chávez-Valenzuela D, Ambriz-Álvarez G, Córdova-Fraga T, Reyes-Grajeda JP, Medina-Contreras Ó, Rodríguez-Cruz F, García-Sierra F, Zúñiga-Sánchez P, Gutiérrez-Gutiérrez AM, Arellanes-Robledo J, Basurto-Islas G\
[*Bioelectromagnetics* 43(4), 225-44](https://onlinelibrary.wiley.com/doi/10.1002/bem.22400)

Homogeneous extremely low-frequency electromagnetic fields (ELF-EMFs) alter biological phenomena, including the cell phenotype and proliferation rate. Heterogenous vortex magnetic fields (VMFs), a new approach of exposure to magnetic fields, induce systematic movements on charged biomolecules from target cells; however, the effect of VMFs on living systems remains uncertain. Here, we designed, constructed, and characterized an ELF-VMF-modified Rodin's coil to expose SH-SY5Y cells. Samples were analyzed by performing 2D-differential-gel electrophoresis, identified by MALDI-TOF/TOF, validated by western blotting, and characterized by confocal microscopy. A total of 106 protein spots were differentially expressed; 40 spots were downregulated and 66 were upregulated in the exposed cell proteome, compared to the control cell proteome. The identified spots are associated with cytoskeleton and cell viability proteins, and according to the protein-protein interaction network, a significant interaction among them was found. Our data revealed a decrease in cell survival associated with apoptotic cells without effects on the cell cycle, as well as evident changes in the cytoskeleton. We demonstrated that ELF-VMFs, at a specific frequency and exposure time, alter the cell proteome and structurally affect the target cells. This is the first report showing that VMF application might be a versatile system for testing different hypotheses in living systems, using appropriate exposure parameters.
:::

::: {.callout-note collapse="true"}
## Proteomic and functional analysis of the effects of quinoxaline derivatives on *Entamoeba histolytica*

Avila-Bonilla RG, López-Sandoval Á, Soto-Sánchez J, Marchat LA, Rivera G, Medina-Contreras O, Ramírez-Moreno E\
[*Front Cell Infect Microbiol* 12, 887647](https://www.frontiersin.org/articles/10.3389/fcimb.2022.887647/full)

Quinoxalines are heterocyclic compounds that contain a benzene ring and a pyrazine ring. The oxidation of both nitrogen of the pyrazine ring results in quinoxaline derivatives (QdNO), which exhibit a variety of biological properties, including antiparasitic activity. However, its activity against Entamoeba histolytica, the protozoan that causes human amebiasis, is poorly understood. Recently, our group reported that various QdNOs produce morphological changes in E. histolytica trophozoites, increase reactive oxygen species, and inhibit thioredoxin reductase activity. Notably, T-001 and T-017 derivatives were among the QdNOs with the best activity. In order to contribute to the characterization of the antiamebic effect of QdNOs, in this work we analyzed the proteomic profile of E. histolytica trophozoites treated with the QdNOs T-001 and T-017, and the results were correlated with functional assays. A total number of 163 deregulated proteins were found in trophozoites treated with T-001, and 131 in those treated with T-017. A set of 21 overexpressed and 24 under-expressed proteins was identified, which were mainly related to cytoskeleton and intracellular traffic, nucleic acid transcription, translation and binding, and redox homeostasis. Furthermore, T-001 and T-017 modified the virulence of trophozoites, since they altered their erythrophagocytosis, migration, adhesion and cytolytic capacity. Our results show that in addition to alter reactive oxygen species, and thioredoxin reductase activity, T-001 and T-017 affect essential functions related to the actin cytoskeleton, which eventually affects *E. histolytica* virulence and survival.
:::

::: {.callout-note collapse="true"}
## Isthmin 1 is expressed by progenitor-like cells in the lung: phenotypical analysis of Isthmin 1^+^ hematopoietic stem-like cells in homeostasis and during infection

Rivera-Torruco G, Martínez-Mendiola CA, Angeles-Floriano T, Jaimes-Ortega GA, Maravillas-Montero JL, García-Contreras R, González Y, Juárez E, Nava P, Ortiz-Navarrete V, Medina-Contreras O, Licona-Limón P, Valle-Rios R\
[*J Immunol Res* 2022, 2909487](https://www.hindawi.com/journals/jir/2022/2909487/)

The process by which blood cells are generated has been widely studied in homeostasis and during pathogen-triggered inflammatory response. Recently, murine lungs have been shown to be a significant source of hematopoietic progenitors in a process known as extramedullary hematopoiesis. Using multiparametric flow cytometry, we have identified mesenchymal, endothelial, and hematopoietic progenitor cells that express the secreted small protein Isthmin 1 (ISM1). Further characterization of hematopoietic progenitor cells indicated that ISM1^+^ Lineage^-^ Sca-1^+^ c-kit^+^ (ISM1^+^ LSK) cells are enriched in short-term hematopoietic stem cells (ST-HSCs). Moreover, most Sca-1+ ISM1+ cells express the residence marker CD49a, and this correlated with their localization in the extravascular region of the lung, indicating that ISM1^+^ cells are lung-resident cells. We also observed that ISM1^+^ cells express TLR4, TLR5, and TLR9, and, in a mouse model of sepsis induced by P. aeruginosa, we observed that all the LSK and ISM1^+^LSK cells were affected. We conclude that ISM1 is a novel biomarker associated with progenitor-like cells. ISM1+ cells are involved in the response to a bacterial challenge, suggesting an association between ISM1-producing cells and dangerous inflammatory responses like sepsis.
:::

::: {.callout-note collapse="true"}
## Genomic characterization of two bacteriophages (vB_EcoS-phiEc3 and vB_EcoS-phiEc4) belonging to the genus Kagunavirus with lytic activity against uropathogenic *Escherichia coli*

Rodea GE, González-Villalobos E, Medina-Contreras O, Castelán-Sánchez HG, Aguilar-Rodea P, Velázquez-Guadarrama N, Hernández-Chiñas U, Eslava-Campos CA, Balcázar JL, Molina-López J\
[*Microb Pathog* 165, 105494](https://www.sciencedirect.com/science/article/abs/pii/S0882401022001073)

In this study, the genomes of two lytic bacteriophages, vB_EcoS-phiEc3 and vB_EcoS-phiEc4, were sequenced and characterized using bioinformatics approaches. Whole-genome analysis showed that both phages belonged to the Kagunavirus genus, Guernseyvirinae subfamily and Siphoviridae family. Moreover, their genomes had 45, 288 bp and 44,540 bp, and G + C content of 48.42% and 50.04%, respectively. The genome of vB_EcoS-phiEc3 harbored 80 protein coding sequences (CDSs), whereas vB_EcoS-phiEc4 harbored 75 CDSs. Among them, 50 CDSs in vB_EcoS-phiEc3 and 44 CDSs in vB_EcoS-phiEc4 were considered as functional genes. Their lytic activity against multidrug-resistant uropathogenic Escherichia coli (UPEC) strains, as well as the absence of antibiotic resistance genes, lysogenic and virulence genes, enable vB_EcoS-phiEc3 and vB_EcoS-phiEc4 as a safe therapy option against UPEC infections.
:::

::: {.callout-note collapse="true"}
## Interleukin-1 receptor-like 2: one receptor, three agonists, and many implications

Manzanares-Meza LD, Valle-Rios R, Medina-Contreras O\
[*J Interferon Cytokine Res* 42(2), 49-61](https://www.liebertpub.com/doi/10.1089/jir.2021.0173)

The interleukin (IL)-1 superfamily of cytokines comprises 11 pro- and anti-inflammatory cytokines, which play essential roles during the immune response. Several pathogenic pathways are initiated by IL-1RL2 (interleukin 1 receptor-like 2) signaling, also known as IL-36R, in the skin, lungs, and gut. IL-36 cytokines promote the secretion of proinflammatory cytokines and chemokines, upregulation of antimicrobial peptides, proliferation mediators, and adhesion molecules on endothelial cells. In addition, the IL-36-IL-1RL2 axis has an essential role against viral infections, including a potential role in COVID-19 pathology. The evidence presented in this review highlights the importance of the axis IL-36-IL-1RL2 in the development of several inflammation-related diseases and the healing process. It suggests that IL-1RL2 ligands have specific roles depending on the tissue or cell source. However, there is still much to discover about this cytokine family, their functions in other organs, and how they accomplish a dual effect in inflammation and healing.
:::

::: {.callout-note collapse="true"}
## Evaluation and quantification of micro epithelial gaps in the colonic mucosa using immunofluorescence staining

Castro-Martínez F, Encarnación-García MDR, Candelario-Martinez A, Medina-Contreras O, Patiño-Lopez G, Schnoor M, Nava P\
[*J Vis Exp* 2021(172)](https://www.jove.com/es/t/62204/evaluation-quantification-micro-epithelial-gaps-colonic-mucosa-using)

Epithelial cells lining the intestinal mucosa create a physical barrier that separates the luminal content from the interstitium. Epithelial barrier impairment has been associated with the development of various pathologies such as inflammatory bowel diseases (IBD). In the inflamed mucosa, superficial erosions or micro-erosions that corrupt epithelial monolayers correspond to sites of high permeability. Several mechanisms have been implicated in the formation of micro-erosions including cell shedding and apoptosis. These micro-erosions often represent microscopic epithelial gaps randomly distributed in the colon. Visualization and quantification of those epithelial gaps has emerged as an important tool to investigate intestinal epithelial barrier function. Here, we describe a new method to visualize the specific location of where transcellular and paracellular permeability is enhanced in the inflamed colonic mucosa. In this assay, we apply a 10 kDa fluorescent dye conjugated to a lysine fixable dextran to visualize high permeability regions (HPR) in the colonic mucosa. Additional use of cell death markers revealed that HPR encompass apoptotic foci where epithelial extrusion/shedding occurs. The protocol described here provides a simple but effective approach to visualize and quantify micro-erosions in the intestine, which is a very useful tool in disease models, in which the intestinal epithelial barrier is compromised.
:::

::: {.callout-note collapse="true"}
## Comparative transcriptomes of the body wall of wild and farmed sea cucumber *Isostichopus badionotus*

Martín-Hernández R, Rodríguez-Canul R, Kantún-Moreno N, Olvera-Novoa MA, Medina-Contreras O, Garikoitz-Legarda C, Triviño JC, Zamora-Briseño JA, May-Solis V, Poot-Salazar A, Pérez-Vega JA, Gil-Zamorano J, Grant G, Dávalos A, Olivera-Castillo L\
[*Int J Mol Sci* 22(8), 3882](https://www.mdpi.com/1422-0067/22/8/3882)

Overfishing of sea cucumber Isostichopus badionotus from Yucatan has led to a major population decline. They are being captured as an alternative to traditional species despite a paucity of information about their health-promoting properties. The transcriptome of the body wall of wild and farmed I. badionotus has now been studied for the first time by an RNA-Seq approach. The functional profile of wild I. badionotus was comparable with data in the literature for other regularly captured species. In contrast, the metabolism of first generation farmed I. badionotus was impaired. This had multiple possible causes including a sub-optimal growth environment and impaired nutrient utilization. Several key metabolic pathways that are important in effective handling and accretion of nutrients and energy, or clearance of harmful cellular metabolites, were disrupted or dysregulated. For instance, collagen mRNAs were greatly reduced and deposition of collagen proteins impaired. Wild I. badionotus is, therefore, a suitable alternative to other widely used species but, at present, the potential of farmed I. badionotus is unclear. The environmental or nutritional factors responsible for their impaired function in culture remain unknown, but the present data gives useful pointers to the underlying problems associated with their aquaculture.
:::

::: {.callout-note collapse="true"}
## IL-36R signaling integrates innate and adaptive immune-mediated protection against enteropathogenic bacteria

Ngo VL, Abo H, Kuczma M, Szurek E, Moore N, Medina-Contreras O, Nusrat A, Merlin D, Gewirtz AT, Ignatowicz L, Denning TL\
[*Proc Natl Acad Sci USA* 117(44):27540-8](https://www.pnas.org/doi/full/10.1073/pnas.2004484117)

Enteropathogenic bacterial infections are a global health issue associated with high mortality, particularly in developing countries. Efficient host protection against enteropathogenic bacterial infection is characterized by coordinated responses between immune and nonimmune cells. In response to infection in mice, innate immune cells are activated to produce interleukin (IL)-23 and IL-22, which promote antimicrobial peptide (AMP) production and bacterial clearance. IL-36 cytokines are proinflammatory IL-1 superfamily members, yet their role in enteropathogenic bacterial infection remains poorly defined. Using the enteric mouse pathogen, *C.rodentium*, we demonstrate that signaling via IL-36 receptor (IL-36R) orchestrates a crucial innate-adaptive immune link to control bacterial infection. IL-36R-deficient mice (Il1rl2^-/-^) exhibited significant impairment in expression of IL-22 and AMPs, increased intestinal damage, and failed to contain *C. rodentium* compared to controls. These defects were associated with failure to induce IL-23 and IL-6, two key IL-22 inducers in the early and late phases of infection, respectively. Treatment of Il1rl2^-/-^ mice with IL-23 during the early phase of *C. rodentium* infection rescued IL-22 production from group 3 innate lymphoid cells (ILCs), whereas IL-6 administration during the late phase rescued IL-22-mediated production from CD4^+^ T cell, and both treatments protected Il1rl2^-/-^ mice from uncontained infection. Furthermore, IL-36R-mediated IL-22 production by CD4^+^ T cells was dependent upon NF$\kappa$B-p65 and IL-6 expression in dendritic cells (DCs), as well as aryl hydrocarbon receptor (AhR) expression by CD4^+^ T cells. Collectively, these data demonstrate that the IL-36 signaling pathway integrates innate and adaptive immunity leading to host defense against enteropathogenic bacterial infection.
:::

::: {.callout-note collapse="true"}
## Nucleoredoxin interaction with flightless-I/actin complex is differentially altered in alcoholic liver disease

Alarcón-Sánchez BR, Guerrero-Escalera D, Rosas-Madrigal S, Ivette Aparicio-Bautista D, Reyes-Gordillo K, Lakshman MR, Ortiz-Fernández A, Quezada H, Medina-Contreras O, Villa-Treviño S, Isael Pérez-Carreón J, Arellanes-Robledo J\
[*Basic Clin Pharmacol Toxicol* 127(5), 389-404](https://onlinelibrary.wiley.com/doi/10.1111/bcpt.13451)

Alcoholic liver disease (ALD) may be attributed to multiple hits driving several alterations. The aim of this work was to determine whether nucleoredoxin (NXN) interacts with flightless-I (FLII)/actin complex and how this ternary complex is altered during ALD progression induced by different ALD models. ALD was recapitulated in C57BL/6J female mice by the well-known ALD Lieber-DeCarli model, and by an in vitro human co-culture system overexpressing NXN. The effects of ethanol and low doses of lipopolysaccharides (LPS) and diethylnitrosamine (DEN) were also evaluated in vivo as a first approach of an ALD multi-hit protocol. We demonstrated that NXN interacts with FLII/actin complex. This complex was differentially altered in ALD in vivo and in vitro, and NXN overexpression partially reverted this alteration. We also showed that ethanol, LPS and DEN synergistically induced liver structural disarrangement, steatosis and inflammatory infiltration accompanied by increased levels of proliferation (Ki67), ethanol metabolism (CYP2E1), hepatocarcinogenesis (GSTP1) and LPS-inducible (MYD88 and TLR4) markers. In summary, we provide evidence showing that NXN/FLII/actin complex is involved in ALD progression and that NXN might be involved in the regulation of FLII/actin-dependent cellular functions. Moreover, we present a promising first approach of a multi-hit protocol to better recapitulate ALD pathogenesis.
:::

::: {.callout-note collapse="true"}
## Molecular epidemiology of *Acinetobacter calcoaceticus*-*Acinetobacter baumannii* complex isolated from children at the Hospital Infantil de México Federico Gómez

Mancilla-Rojano J, Ochoa SA, Reyes-Grajeda JP, Flores V, Medina-Contreras O, Espinosa-Mazariego K, Parra-Ortega I, Rosa-Zamboni D, Castellanos-Cruz MDC, Arellano-Galindo J, Cevallos MA, Hernández-Castro R, Xicohtencatl-Cortes J, Cruz-Córdova A\
[*Front Microbiol* 11, 576673](https://onlinelibrary.wiley.com/doi/10.1111/bcpt.13451)

The *Acinetobacter calcoaceticus*-*baumannii* (Acb) complex is regarded as a group of phenotypically indistinguishable opportunistic pathogens responsible for mainly causing hospital-acquired pneumonia and bacteremia. The aim of this study was to determine the frequency of isolation of the species that constitute the Acb complex, as well as their susceptibility to antibiotics, and their distribution at the Hospital Infantil de Mexico Federico Gomez (HIMFG). A total of 88 strains previously identified by Vitek 2®, 40 as *Acinetobacter baumannii* and 48 as Acb complex were isolated from 52 children from 07, January 2015 to 28, September 2017. *A. baumannii* accounted for 89.77% (79/88) of the strains; *Acinetobacter pittii*, 6.82% (6/88); and *Acinetobacter nosocomialis*, 3.40% (3/88). Most strains were recovered mainly from patients in the intensive care unit (ICU) and emergency wards. Blood cultures (BC) provided 44.32% (39/88) of strains. The 13.63% (12/88) of strains were associated with primary bacteremia, 3.4% (3/88) with secondary bacteremia, and 2.3% (2/88) with pneumonia. In addition, 44.32% (39/88) were multidrug-resistant (MDR) strains and, 11.36% (10/88) were extensively drug-resistant (XDR). All strains amplified the bla OXA-51 gene; 51.13% (45/88), the bla OXA-23 gene; 4.54% (4/88), the bla OXA-24 gene; and 2.27% (2/88), the bla OXA-58 gene. Plasmid profiles showed that the strains had 1-6 plasmids. The strains were distributed in 52 pulsotypes, and 24 showed identical restriction patterns, with a correlation coefficient of 1.0. Notably, some strains with the same pulsotype were isolated from different patients, wards, or years, suggesting the persistence of more than one clone. Twenty-seven sequence types (STs) were determined for the strains based on a Pasteur multilocus sequence typing (MLST) scheme using massive sequencing; the most prevalent was ST 156 (27.27%, 24/88). The Clustered Regularly Interspaced Short Palindromic Repeats (CRISPR)-Cas I-Fb system provided amplification in *A. baumannii* and *A. pittii* strains (22.73%, 20/88). This study identified an increased number of MDR strains and the relationship among strains through molecular typing. The data suggest that more than one strain could be causing an infection in some patient. The implementation of molecular epidemiology allowed the characterization of a set of strains and identification of different attributes associated with its distribution in a specific environment.
:::

::: {.callout-note collapse="true"}
## The role of the oncogenic Rab35 in cancer invasion, metastasis, and immune evasion, especially in leukemia

Villagomez FR, Medina-Contreras O, Cerna-Cortes JF, Patino-Lopez G\
[*Small GTPases* 11(5), 334-45](https://www.tandfonline.com/doi/full/10.1080/21541248.2018.1463895)

The study of cancer has allowed researchers to describe some biological characteristics that tumor cells acquire during their development, known as the "hallmarks of cancer" but more research is needed to expand our knowledge about cancer biology and to generate new strategies of treatment. The role that RabGTPases might play in some hallmarks of cancer represents interesting areas of study since these proteins are frequently altered in cancer. However, their participation is not well known. Recently, Rab35was recognized as an oncogenic RabGTPase and and because of its association with different cellular functions, distinctly important in immune cells, a possible role of Rab35 in leukemia can be suggested. Nevertheless, the involvement of Rab35 in cancer remains poorly understood and its possible specific role in leukemia remains unknown. In this review, we analyze general aspects of the participation of RabGTPases in cancer, and especially, the plausible role of Rab35 in leukemia.
:::

::: {.callout-note collapse="true"}
## A glycosaminoglycan-rich fraction from sea cucumber *Isostichopus badionotus* has potent anti-inflammatory properties *in vitro* and *in vivo*

Olivera-Castillo L, Grant G, Kantún-Moreno N, Barrera-Pérez HA, Montero J, Olvera-Novoa MA, Carrillo-Cocom LM, Acevedo JJ, Puerto-Castillo C, May Solís V, Pérez-Vega JA, Gil-Zamorano J, Hernández-Garibay E, Fernández-Herrera MA, Pérez-Tapia M, Medina-Contreras O, Villanueva-Toledo JR, Rodriguez-Canul R, Dávalos A\
[*Nutrients* 12(6), 1698](https://www.mdpi.com/2072-6643/12/6/1698)

Sea cucumber body wall contains several naturally occurring bioactive components that possess health-promoting properties. Isostichopus badionotus from Yucatan, Mexico is heavily fished, but little is known about its bioactive constituents. We previously established that I. badionotus meal had potent anti-inflammatory properties in vivo. We have now screened some of its constituents for anti-inflammatory activity in vitro. Glycosaminoglycan and soluble protein preparations reduced 12-O-tetradecanoylphorbol-13-acetate (TPA)-induced inflammatory responses in HaCaT cells while an ethanol extract had a limited effect. The primary glycosaminoglycan (fucosylated chondroitin sulfate; FCS) was purified and tested for anti-inflammatory activity in vivo. FCS modulated the expression of critical genes, including NF-ĸB, TNFα, iNOS, and COX-2, and attenuated inflammation and tissue damage caused by TPA in a mouse ear inflammation model. It also mitigated colonic colitis caused in mice by dextran sodium sulfate. FCS from I. badionotus of the Yucatan Peninsula thus had strong anti-inflammatory properties in vivo.
:::

::: {.callout-note collapse="true"}
## Immunoendocrine peripheral effects induced by atypical antipsychotics

Alvarez-Herrera S, Escamilla R, Medina-Contreras O, Saracco R, Flores Y, Hurtado-Alvarado G, Maldonado-García JL, Becerril-Villanueva E, Pérez-Sánchez G, Pavón L\
[*Front Endocrinol* 11, 195](https://www.frontiersin.org/articles/10.3389/fendo.2020.00195/full)

Atypical antipsychotics (AAP) or second-generation antipsychotics are the clinical option for schizophrenia treatment during acute psychoses, but they are also indicated for maintenance during lifetime, even though they are being used for other psychiatric conditions in clinical practice such as affective disorders and autism spectrum disorder, among others. These drugs are differentiated from typical antipsychotics based on their clinical profile and are a better choice because they cause fewer side effects regarding extrapyramidal symptoms (EPS). Even though they provide clear therapeutic benefits, AAP induce peripheral effects that trigger phenotypic, functional, and systemic changes outside the Central Nervous System (CNS). Metabolic disease is frequently associated with AAP and significantly impacts the patient's quality of life. However, other peripheral changes of clinical relevance are present during AAP treatment, such as alterations in the immune and endocrine systems as well as the intestinal microbiome. These less studied alterations also have a significant impact in the patient's health status. This manuscript aims to revise the peripheral immunological, endocrine, and intestinal microbiome changes induced by AAP consumption recommended in the clinical guidelines for schizophrenia and other psychiatric disorders.
:::

::: {.callout-note collapse="true"}
## Intestinal response to dietary manganese depletion in Drosophila

Vásquez-Procopio J, Osorio B, Cortés-Martínez L, Hernández-Hernández F, Medina-Contreras O, Ríos-Castro E, Comjean A, Li F, Hu Y, Mohr S, Perrimon N, Missirlis F\
[*Metallomics* 12(2), 218-40](https://academic.oup.com/metallomics/article/12/2/218/5961849?login=false)

Manganese is considered essential for animal growth. Manganese ions serve as cofactors to three mitochondrial enzymes: superoxide dismutase (Sod2), arginase and glutamine synthase, and to glycosyltransferases residing in the Golgi. In Drosophila melanogaster, manganese has also been implicated in the formation of ceramide phosphoethanolamine, the insect's sphingomyelin analogue, a structural component of cellular membranes. Manganese overload leads to neurodegeneration and toxicity in both humans and Drosophila. Here, we report specific absorption and accumulation of manganese during the first week of adulthood in flies, which correlates with an increase in Sod2 activity during the same period. To test the requirement of dietary manganese for this accumulation, we generated a Drosophila model of manganese deficiency. Due to the lack of manganese-specific chelators, we used chemically defined media to grow the flies and deplete them of the metal. Dietary manganese depletion reduced Sod2 activity. We then examined gene and protein expression changes in the intestines of manganese depleted flies. We found adaptive responses to the presumed loss of known manganese-dependent enzymatic activities: less glutamine synthase activity (amination of glutamate to glutamine) was compensated by 50% reduction in glutaminase (deamination of glutamine to glutamate); less glycosyltransferase activity, predicted to reduce protein glycosylation, was compensated by 30% reduction in lysosomal mannosidases (protein deglycosylating enzymes); less ceramide phosphoethanolamine synthase activity was compensated by 30% reduction in the Drosophila sphingomyeline phospodiesterase, which could catabolize ceramide phosphoethanolamine in flies. Reduced Sod2 activity, predicted to cause superoxide-dependent iron-sulphur cluster damage, resulted in cellular iron misregulation.
:::

::: {.callout-note collapse="true"}
## Immunonutrition in cervical cancer: immune response modulation by diet

Medina-Contreras O, Luvián-Morales J, Valdez-Palomares F, Flores-Cisneros L, Sánchez-López MS, Soto-Lugo JH, Castro-Eguiluz D\
[*Rev Invest Clin* 72(4), 219-30](https://clinicalandtranslationalinvestigation.com/frame_esp.php?id=305)

In the development of cervical cancer (CC), the immune response plays an essential role, from the elimination of human papillomavirus (HPV) infection to the response against the tumor. For optimal function of the immune response, various factors are required, one of the most important being an adequate nutrition. The complex interaction between nutrients and microbiota maintains the immune system in homeostasis and in case of infection, it provides the ability to fight against pathogen invasion, as occurs in HPV infection. The purpose of this article is to describe the role of diet, food, and specific nutrients in the immune response from the onset of infection to progression to precancerous lesions and CC, as well as the role of diet and nutrition during oncological treatment. The immunomodulatory role of microbiota is also discussed. A detailed analysis of the evidence leads us to recommend a nutritional pattern very similar to the Mediterranean diet or the prudent diet for an optimal immune response. Moreover, pre- and probiotics favorably modulate the microbiota and induce preventive and therapeutic effects against cancer.
:::

<!--
Cetina-Pérez L, Castro-Eguiluz D. CONSENSUS REPORT ON THE PREVENTION, DIAGNOSIS, AND TREATMENT OF CERVICAL CANCER - A PERSPECTIVE FROM THE IMMUNE SYSTEM TOWARD IMMUNOTHERAPY. Rev Invest Clin. 2020;72(4):185-187. doi: 10.24875/RIC.20000129. PMID: 33064681.

Cetina-Pérez L, Castro-Eguiluz D. Consensus Report on the Prevention, Diagnosis, and Treatment of Cervical Cancer - a Perspective from the Immune System Toward Immunotherapy. Rev Invest Clin. 2020 May 7;73(3). Epub ahead of print. PMID: 32488222.

Cérbulo-Vázquez A, Arriaga-Pizano L, Cruz-Cureño G, Boscó-Gárate I, Ferat-Osorio E, Pastelin-Palacios R, Figueroa-Damian R, Castro-Eguiluz D, Mancilla-Ramirez J, Isibasi A, López-Macías C. Medical Outcomes in Women Who Became Pregnant after Vaccination with a Virus-Like Particle Experimental Vaccine against Influenza A (H1N1) 2009 Virus Tested during 2009 Pandemic Outbreak. Viruses. 2019 Sep 17;11(9):868. doi: 10.3390/v11090868. PMID: 31533277; PMCID: PMC6783846.

Sánchez M, Castro-Eguiluz D, Luvián-Morales J, Jiménez-Lima R, Aguilar-Ponce JL, Isla-Ortiz D, Cetina L. Deterioration of nutritional status of patients with locally advanced cervical cancer during treatment with concomitant chemoradiotherapy. J Hum Nutr Diet. 2019 Aug;32(4):480-491. doi: 10.1111/jhn.12649. Epub 2019 Apr 1. PMID: 30938007.

Serralde-Zúñiga A, Castro-Eguiluz D, Aguilar-Ponce JL, Peña-Ruiz AA, Castro-Gutiérrez JV, Rivera-Rivera S, Aranda-Flores C, Casique-Pérez V, Alarcón-Barrios SE, de la Garza-Salazar J, Sánchez-López M, Dueñas-González A. Epidemiological Data on the Nutritional Status of Cancer Patients Receiving Treatment with Concomitant Chemoradiotherapy, Radiotherapy or Sequential Chemoradiotherapy to the Abdominopelvic Area. Rev Invest Clin. 2018;70(3):117-120. doi: 10.24875/RIC.18002523. PMID: 29943775.

Flores-Cisneros L, Castro-Eguiluz D, Reyes-Barretero DY, Jaimes E, Cano-Blanco C, Avendaño-Pérez C, Carbajal-López B, Sánchez-López M, Mota-García A, Gallardo-Rincón D, Inzunza-Soto M, Hernandez-Quintero C, Cetina-Pérez L. Effects of Dietary Components During and After Concomitant Chemoradiotherapy, Radiotherapy, or Sequential Chemoradiotherapy to the Abdominopelvic Area. Rev Invest Clin. 2018;70(3):126-129. doi: 10.24875/RIC.18002525. PMID: 29943774.

Castro-Eguiluz D, Leyva-Islas JA, Luvian-Morales J, Martínez-Roque V, Sánchez-López M, Trejo-Durán G, Jiménez-Lima R, Leyva-Rendón FJ. Nutrient Recommendations for Cancer Patients Treated with Pelvic Radiotherapy, with or without Comorbidities. Rev Invest Clin. 2018;70(3):130-135. doi: 10.24875/RIC.18002526. PMID: 29943773.

Castillo-Martínez L, Castro-Eguiluz D, Copca-Mendoza ET, Pérez-Camargo DA, Reyes-Torres CA, Ávila EA, López-Córdova G, Fuentes-Hernández MR, Cetina-Pérez L, Milke-García MDP. Nutritional Assessment Tools for the Identification of Malnutrition and Nutritional Risk Associated with Cancer Treatment. Rev Invest Clin. 2018;70(3):121-125. doi: 10.24875/RIC.18002524. PMID: 29943772.

Cetina-Pérez L, Serrano-Olvera A, Flores-Cisneros L, Jiménez-Lima R, Alvarado-Silva C, Díaz-Romero MDC, Morales-Vásquez F, Muñoz-González DE, Mota-García A, Chávez-Fierro OA, Jaramillo-Manzur SC, de la Garza-Salazar J, Castro-Eguiluz D, Meneses-García A. Epidemiological Profile, Gastrointestinal Toxicity, and Treatment of Pelvic Cancers in Patients Managed with Radiotherapy to the Abdominal Pelvic Area. Rev Invest Clin. 2018;70(3):112-116. doi: 10.24875/RIC.18002528. PMID: 29943771.

Cetina-Pérez L, Castro-Eguiluz D, Oñate-Ocaña LF. Nutrition in Patients with Cancer Treated with Chemo-radiotherapy to the Abdominopelvic Area. A consensus report. Rev Invest Clin. 2018;70(3):109-111. doi: 10.24875/RIC.18002521. PMID: 29943770.

Serna-Thomé G, Castro-Eguiluz D, Fuchs-Tarlovsky V, Sánchez-López M, Delgado-Olivares L, Coronel-Martínez J, Molina-Trinidad EM, de la Torre M, Cetina-Pérez L. Use of Functional Foods and Oral Supplements as Adjuvants in Cancer Treatment. Rev Invest Clin. 2018;70(3):136-146. doi: 10.24875/RIC.18002527. PMID: 29943769.

Rosales-Reyes R, Pérez-López A, Sánchez-Gómez C, Hernández-Mote RR, Castro-Eguiluz D, Ortiz-Navarrete V, Alpuche-Aranda CM. Salmonella infects B cells by macropinocytosis and formation of spacious phagosomes but does not induce pyroptosis in favor of its survival. Microb Pathog. 2012 Jun;52(6):367-74. doi: 10.1016/j.micpath.2012.03.007. Epub 2012 Mar 29. PMID: 22475626.


-->

::: {.callout-note collapse="true"}
## SARS-CoV-2 and influenza: a comparative overview and treatment implications

Manzanares-Meza LD, Medina-Contreras O\
[*Bol Med Hosp Infant Mex* 77(5), 262-273](https://www.bmhim.com/frame_esp.php?id=177)

Severe acute respiratory syndrome coronavirus 2 (SARS-CoV-2) and Alphainfluenzavirus are RNA viruses that cause coronavirus disease-19 and influenza, respectively. Both viruses infect the respiratory tract, show similar symptoms, and use surface proteins to infect the host. Influenza requires hemagglutinin and neuraminidase to infect, whereas SARS-CoV-2 uses protein S. Both viruses depend on a viral RNA polymerase to express their proteins, but only SARS-CoV-2 has a proofreading mechanism, which results in a low mutation rate compared to influenza. E1KC4 and camostat mesylate are potential inhibitors of SARS-CoV-2 S protein, achieving an effect similar to oseltamivir. Due to the SARS-CoV-2 low mutation rate, nucleoside analogs have been developed (such as EIDD-2801), which insert lethal mutations in the viral RNA. Furthermore, the SARS-CoV-2 low mutation rate suggests that a vaccine, as well as the immunity developed in recovered patients, could provide long-lasting protection compared to vaccines against influenza, which are rendered obsolete as the virus mutates.
:::

::: {.callout-note collapse="true"}
## Omeprazole as a potent activator of human cytosolic aldehyde dehydrogenase ALDH1A1

Calleja LF, Belmont-Díaz JA, Medina-Contreras O, Quezada H, Yoval-Sánchez B, Campos-García J, Rodríguez-Zavala JS\
[*Biochim Biophys Acta Gen Subj* 1864(1), 129451](https://www.sciencedirect.com/science/article/abs/pii/S0304416519302375?via%3Dihub)

Accumulation of lipid aldehydes plays a key role in the etiology of human diseases where high levels of oxidative stress are generated. In this regard, activation of aldehyde dehydrogenases (ALDHs) prevents oxidative tissue damage during ischemia-reperfusion processes. Although omeprazole is used to reduce stomach gastric acid production, in the present work this drug is described as the most potent activator of human ALDH1A1 reported yet. Docking analysis was performed to predict the interactions of omeprazole with the enzyme. Recombinant human ALDH1A1 was used to assess the effect of omeprazole on the kinetic properties. Temperature treatment and mass spectrometry were conducted to address the nature of binding of the activator to the enzyme. Finally, the effect of omeprazole was evaluated in an in vivo model of oxidative stress, using E. coli cells expressing the human ALDH1A1. Omeprazole interacted with the aldehyde binding site, increasing 4-6 fold the activity of human ALDH1A1, modified the kinetic properties, altering the order of binding of substrates and release of products, and protected the enzyme from inactivation by lipid aldehydes. Furthermore, omeprazole protected E. coli cells over-expressing ALDH1A1 from the effects of oxidative stress generated by H2O2 exposure, reducing the levels of lipid aldehydes and preserving ALDH activity. Omeprazole can be repositioned as a potent activator of human ALDH1A1 and may be proposed for its use in therapeutic strategies, to attenuate the damage generated during oxidative stress events occurring in different human pathologies.
:::

::: {.callout-note collapse="true"}
## Polymorphisms in adipokines in Mexican children with obesity

Jiménez-Osorio AS, Aguilar-Lucio AO, Cárdenas-Hernández H, Musalem-Younes C, Solares-Tlapechco J, Costa-Urrutia P, Medina-Contreras O, Granados J, Rodríguez-Arellano ME\
[*Int J Endocrinol* 2019, 4764751](https://www.hindawi.com/journals/ije/2019/4764751/)

The high prevalence of childhood obesity in Mexico is alarming in the health-science field. We propose to investigate the contribution of adipokines and cytokines polymorphisms and common BMI/obesity-associated loci, revealed in genome-wide association studies in Caucasian adult cohorts, with childhood obesity. This study included 773 Mexican-Mestizo children (5-15 years old) in a case-control study. The polymorphisms included were ADIPOQ (rs6444174), TNF-α (rs1800750), IL-1β (rs1143643), IL-6 (rs1524107; rs2069845), NEGR1 (rs34305371), SEC16B-RASAL2 (rs10913469), TMEM18 (rs6548238; rs7561317), GNPDA2 (rs16857402), LEP (rs2167270), MTCH2 (rs10838738), LGR4-LIN7C-BDNF (rs925946), BCDIN3D-FAIM2 (rs7138803), FTO (rs62033400), MC4R (rs11872992), MC4R (rs17782313), and KCTD15 (rs29942). No significant contribution was found with adipokines and cytokines polymorphisms in this study. Only both TMEM18 (rs6548238; rs7561317) polymorphisms were found associated with obesity (OR=0.5, P=0.008) and were in linkage disequilibrium (r2=0.87). The linear regression showed that the rs7561317 polymorphism of TMEM18 is negatively associated with obesity. This report highlights the influence of TMEM18 in Mexican-Mestizo children obesity, while adipokine and cytokine polymorphisms were not associated with it.
:::

::: {.callout-note collapse="true"}
## Obesity measured as percent body fat, relationship with body mass index, and percentile curves for Mexican pediatric population

Costa-Urrutia P, Vizuet-Gámez A, Ramirez-Alcántara M, Guillen-González MÁ, Medina-Contreras O, Valdes-Moreno M, Musalem-Younes C, Solares-Tlapechco J, Granados J, Franco-Trecu V, Rodriguez-Arellano ME\
[*PLoS One* 14(2), e0212792](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0212792)

In Mexico, the increase in childhood obesity is alarming. Thus, improving the precision of its diagnosis is expected to impact on disease prevention. We estimated obesity prevalence by bioimpedance-based percent body fat (%BF) and body mass index (BMI) in 1061 girls and 1121 boys, from 3 to 17 years old. Multiple regressions and area under receiver operating curves (AUC) were used to determine the predictive value of BMI on %BF and percentile curves were constructed. Overall obesity prevalence estimated by %BF was 43.7%, and by BMI it was 20.1%; it means that the diagnosis by BMI underestimated around 50% of children diagnosed with obesity by %BF (≥30% for girls, ≥25% for boys). The fat mass excess is further underestimated in boys than in girls when using the standard BMI classification. The relationship between %BF and BMI was strong in school children and adolescents (all cases R2\>0.70), but not in preschool children (girls R2 = 0.57, boys R2 = 0.23). AUCs showed greater discriminative power of BMI to detect %BF obesity in school children and adolescents (all cases AUC≥0.90) than in preschool children (girls AUC = 0.86; boys AUC = 0.70). Growth percentile charts showed that girls aged 9-17 years and boys aged 8-17 years presented fat excess from the 50th percentile and above. We suggested to change the BMI cut-off for them, considering values at the 75th percentile as overweight, and values at the 85th percentile as obesity, as previously recommended for Mexican children. Improving obesity diagnosis will allow greater efficiency when searching for comorbidities in clinical practice.
:::

::: {.callout-note collapse="true"}
## Common polymorphisms linked to obesity and cardiovascular disease in Europeans and Asians are associated with Type 2 Diabetes in Mexican mestizos

Jiménez-Osorio AS, Musalem-Younes C, Cárdenas-Hernández H, Solares-Tlapechco J, Costa-Urrutia P, Medina-Contreras O, Granados J, López-Saucedo C, Estrada-Garcia T, Rodríguez-Arellano ME\
[*Medicina* 55(2), 40](https://www.mdpi.com/1648-9144/55/2/40)

Type 2 diabetes (T2D) is a major problem of public health in Mexico. We investigated the influence of five polymorphisms, previously associated with obesity and cardiovascular disease in Europeans and Asians, on T2D in Mexican Mestizos. A total of 1358 subjects from 30 to 85 years old were genotyped for five loci: CXCL12 rs501120; CDNK2A/B rs1333049; HNF-1α rs2259816; FTO rs9939609; and LEP rs7799039. We used logistic regressions to test the effect of each locus on T2D in two case⁻control groups with obesity and without obesity. Also, linear regression models on glucose and glycated hemoglobin (HbA1c) were carried out on the whole sample, adjusted by age, gender, and body mass index. The CXCL12 rs501120 C allele (OR = 1.96, p = 0.02), the FTO rs9939609 A allele (OR = 2.20, p = 0.04) and the LEP rs7799039 A allele (OR = 0.6, p = 0.03) were significantly associated with T2D in obesity case⁻control group. No significant association was found in the non-obesity case⁻control group. The linear regression model showed that CDNK2A/B rs1333049 C allele (β = 0.4, p = 0.03) and FTO rs9939609 A allele (β = 0.5, p = 0.03), were significantly associated with HbA1c, but no association was found among the loci with the glucose levels. Polymorphisms previously linked with obesity and cardiovascular events were also associated with T2D and high levels of HbA1c. Furthermore, we must point at the fact that this is the first report where polymorphisms CXCL12 rs501120 and LEP rs7799039 are associated with T2D in subjects with obesity.
:::

::: {.callout-note collapse="true"}
## Myosin 1F regulates M1-polarization by stimulating intercellular adhesion in macrophages

Piedra-Quintero ZL, Serrano C, Villegas-Sepúlveda N, Maravillas-Montero JL, Romero-Ramírez S, Shibayama M, Medina-Contreras O, Nava P, Santos-Argumedo L\
[*Front Immunol* 9, 3118](https://www.frontiersin.org/articles/10.3389/fimmu.2018.03118/full)

Intestinal macrophages are highly mobile cells with extraordinary plasticity and actively contribute to cytokine-mediated epithelial cell damage. The mechanisms triggering macrophage polarization into a proinflammatory phenotype are unknown. Here, we report that during inflammation macrophages enhance its intercellular adhesion properties in order to acquire a M1-phenotype. Using in vitro and in vivo models we demonstrate that intercellular adhesion is mediated by integrin-αVβ3 and relies in the presence of the unconventional class I myosin 1F (Myo1F). Intercellular adhesion mediated by αVβ3 stimulates M1-like phenotype in macrophages through hyperactivation of STAT1 and STAT3 downstream of ILK/Akt/mTOR signaling. Inhibition of integrin-αVβ3, Akt/mTOR, or lack of Myo1F attenuated the commitment of macrophages into a pro-inflammatory phenotype. In a model of colitis, Myo1F deficiency strongly reduces the secretion of proinflammatory cytokines, decreases epithelial damage, ameliorates disease activity, and enhances tissue repair. Together our findings uncover an unknown role for Myo1F as part of the machinery that regulates intercellular adhesion and polarization in macrophages.
:::

::: {.callout-note collapse="true"}
## The nontoxic cholera B subunit is a potent adjuvant for intradermal DC-targeted vaccination

Antonio-Herrera L, Badillo-Godinez O, Medina-Contreras O, Tepale-Segura A, García-Lozano A, Gutierrez-Xicotencatl L, Soldevila G, Esquivel-Guadarrama FR, Idoyaga J, Bonifaz LC\
[*Front Immunol* 9, 2212](https://www.frontiersin.org/articles/10.3389/fimmu.2018.02212/full)

CD4+ T cells are major players in the immune response against several diseases; including AIDS, leishmaniasis, tuberculosis, influenza and cancer. Their activation has been successfully achieved by administering antigen coupled with antibodies, against DC-specific receptors in combination with adjuvants. Unfortunately, most of the adjuvants used so far in experimental models are unsuitable for human use. Therefore, human DC-targeted vaccination awaits the description of potent, yet nontoxic adjuvants. The nontoxic cholera B subunit (CTB) can be safely used in humans and it has the potential to activate CD4+ T cell responses. However, it remains unclear whether CTB can promote DC activation and can act as an adjuvant for DC-targeted antigens. Here, we evaluated the CTB's capacity to activate DCs and CD4+ T cell responses, and to generate long-lasting protective immunity. Intradermal (i.d.) administration of CTB promoted late and prolonged activation and accumulation of skin and lymphoid-resident DCs. When CTB was co-administered with anti-DEC205-OVA, it promoted CD4+ T cell expansion, differentiation, and infiltration to peripheral nonlymphoid tissues, i.e., the skin, lungs and intestine. Indeed, CTB promoted a polyfunctional CD4+ T cell response, including the priming of Th1 and Th17 cells, as well as resident memory T (RM) cell differentiation in peripheral nonlymphoid tissues. It is worth noting that CTB together with a DC-targeted antigen promoted local and systemic protection against experimental melanoma and murine rotavirus. We conclude that CTB administered i.d. can be used as an adjuvant to DC-targeted antigens for the induction of broad CD4+ T cell responses as well as for promoting long-lasting protective immunity.
:::

::: {.callout-note collapse="true"}
## A cytokine network involving IL-36$\gamma$, IL-23, and IL-22 promotes antimicrobial defense and recovery from intestinal barrier damage

Ngo VL, Abo H, Maxim E, Harusato A, Geem D, Medina-Contreras O, Merlin D, Gewirtz AT, Nusrat A, Denning TL\
[*Proc Natl Acad Sci USA* 115(22), E5076-85](https://www.pnas.org/doi/10.1073/pnas.1718902115)

The gut epithelium acts to separate host immune cells from unrestricted interactions with the microbiota and other environmental stimuli. In response to epithelial damage or dysfunction, immune cells are activated to produce interleukin (IL)-22, which is involved in repair and protection of barrier surfaces. However, the specific pathways leading to IL-22 and associated antimicrobial peptide (AMP) production in response to intestinal tissue damage remain incompletely understood. Here, we define a critical IL-36/IL-23/IL-22 cytokine network that is instrumental for AMP production and host defense. Using a murine model of intestinal damage and repair, we show that IL-36$\gamma$ is a potent inducer of IL-23 both in vitro and in vivo. IL-36$\gamma$-induced IL-23 required Notch2-dependent (CD11b+CD103+) dendritic cells (DCs), but not Batf3-dependent (CD11b-CD103+) DCs or CSF1R-dependent macrophages. The intracellular signaling cascade linking IL-36 receptor (IL-36R) to IL-23 production by DCs involved MyD88 and the NF-κB subunits c-Rel and p50. Consistent with in vitro observations, IL-36R- and IL-36$\gamma$-deficient mice exhibited dramatically reduced IL-23, IL-22, and AMP levels, and consequently failed to recover from acute intestinal damage. Interestingly, impaired recovery of mice deficient in IL-36R or IL-36$\gamma$ could be rescued by treatment with exogenous IL-23. This recovery was accompanied by a restoration of IL-22 and AMP expression in the colon. Collectively, these data define a cytokine network involving IL-36$\gamma$, IL-23, and IL-22 that is activated in response to intestinal barrier damage and involved in providing critical host defense.
:::

::: {.callout-note collapse="true"}
## MALDI imaging: beyond classic diagnosis

Manzanares-Meza LD, Gutiérrez-Román CI, Medina-Contreras O\
[*Bol Med Hosp Infant Mex* 74(3), 212-8](https://www.sciencedirect.com/science/article/pii/S1665114617300291?via%3Dihub)

Mass spectrometry has been the focus of technology development and application for imaging for several decades. Imaging mass spectrometry using matrix-assisted laser desorption ionization is a new and effective tool for molecular studies of complex biological samples such as tissue sections. As histological features remain intact throughout the analysis of a section, distribution maps of multiple analytes can be correlated with histological and clinical features. Spatial molecular arrangements can be assessed without the need for target-specific reagents, allowing the discovery of diagnostic and prognostic markers of different cancer types and enabling the determination of effective therapies.
:::

::: {.callout-note collapse="true"}
## Proteomic changes in a childhood acute lymphoblastic leukemia cell line during the adaptation to vincristine

Guzmán-Ortiz AL, Aparicio-Ozores G, Valle-Rios R, Medina-Contreras O, Patiño-López G, Quezada H\
[*Bol Med Hosp Infant Mex* 74(3), 181-92](https://www.sciencedirect.com/science/article/pii/S1665114617300321?via%3Dihub)

Relapse occurs in approximately 20% of Mexican patients with childhood acute lymphoblastic leukemia (ALL). In this group, chemoresistance may be one of the biggest challenges. An overview of complex cellular processes like drug tolerance can be achieved with proteomic studies. The B-lineage pediatric ALL cell line CCRF-SB was gradually exposed to the chemotherapeutic vincristine until proliferation was observed at 6nM, control cells were cultured in the absence of vincristine. The proteome from each group was analyzed by nanoHPLC coupled to an ESI-ion trap mass spectrometer. The identified proteins were grouped into overrepresented functional categories with the PANTHER classification system. We found 135 proteins exclusively expressed in the presence of vincristine. The most represented functional categories were: Toll receptor signaling pathway, Ras Pathway, B and T cell activation, CCKR signaling map, cytokine-mediated signaling pathway, and oxidative phosphorylation. Our study indicates that signal transduction and mitochondrial ATP production are essential during adaptation of leukemic cells to vincristine, these processes represent potential therapeutic targets.
:::

::: {.callout-note collapse="true"}
## Characterization of Cry toxins from autochthonous *Bacillus thuringiensis* isolates from Mexico

Camacho-Millán R, Aguilar-Medina EM, Quezada H, Medina-Contreras O, Patiño-López G, Cárdenas-Cota HM, Ramos-Payán R\
[*Bol Med Hosp Infant Mex* 74(3), 576673](https://www.sciencedirect.com/science/article/pii/S1665114617300321?via%3Dihub)

Chemical pesticides, widely used in agriculture and vector-borne disease control, have shown toxic effects on the environment and the people in contact with them. Bacillus thuringiensis is a widely used bacterium for alternative and safer control of insect pests. Its toxins are specific for insects but innocuous for mammals and may be used as powerful adjuvants when applied with vaccines. The objective of this work was to characterize some autochthonous B. thuringiensis strains, which could be used for the control of a local pest (Diatraea considerata Heinrich) that affects sugar cane crops in Sinaloa, Mexico. Also, to evaluate these strains as a source of Cry toxins, which may be used in the future as adjuvants for some vaccines. Eight strains from field-collected dead insects were isolated. These were microbiologically identified as B. thuringiensis and confirmed by amplification and sequencing of 16S rDNA. Bioassays were performed to evaluate their pathogenicity against D. considerata, and Cry toxins were identified by proteomic analyses. An increased mortality among larvae infected with strain Bt-D was observed, and its toxin was identified as Cry1Ac. The observed data showed that the selected strain was pathogenic to D. considerata and seemed to produce Cry1Ac protein, which has been reported as an adjuvant in different types of immunization.
:::

::: {.callout-note collapse="true"}
## The pro-inflammatory cytokines IFN$\gamma$/TNF$\alpha$ increase chromogranin A-positive neuroendocrine cells in the colonic epithelium

Hernández-Trejo JA, Suárez-Pérez D, Gutiérrez-Martínez IZ, Fernandez-Vargas OE, Serrano C, Candelario-Martínez AA, Meraz-Ríos MA, Citalán-Madrid AF, Hernández-Ruíz M, Reyes-Maldonado E, Valle-Rios R, Feintuch-Unger JH, Schnoor M, Villegas-Sepúlveda N, Medina-Contreras O, Nava P\
[*Biochem J* 473(21), 3805-18](https://portlandpress.com/biochemj/article-abstract/473/21/3805/49637/The-pro-inflammatory-cytokines-IFN-TNF-increase?redirectedFrom=fulltext)

The gastrointestinal tract is the largest hormone-producing organ in the body due to a specialized cell population called enteroendocrine cells (EECs). The number of EECs increases in the mucosa of inflammatory bowel disease patients; however, the mechanisms responsible for these changes remain unknown. Here, we show that the pro-inflammatory cytokines interferon $\gamma$ (IFN$\gamma$) and tumor necrosis factor α (TNFα) or dextran sulfate sodium (DSS)-induced colitis increase the number of EECs producing chromogranin A (CgA) in the colonic mucosa of C57BL/6J mice. CgA-positive cells were non-proliferating cells enriched with inactive phosphatase and tensin homolog deleted on chromosome 10 (PTEN) and autophagy markers. Moreover, inhibition of Akt and autophagy prevented the increase in CgA-positive cells after IFN$\gamma$/TNFα treatment. Similarly, we observed that CgA-positive cells in the colonic mucosa of patients with colitis expressed Akt and autophagy markers. These findings suggest that Akt signaling and autophagy control differentiation of the intestinal EEC lineage during inflammation.
:::

::: {.callout-note collapse="true"}
## 14-3-3 Proteins regulate Akt Thr308 phosphorylation in intestinal epithelial cells

Gómez-Suárez M, Gutiérrez-Martínez IZ, Hernández-Trejo JA, Hernández-Ruiz M, Suárez-Pérez D, Candelario A, Kamekura R, Medina-Contreras O, Schnoor M, Ortiz-Navarrete V, Villegas-Sepúlveda N, Parkos C, Nusrat A, Nava P\
[*Cell Death Differ* 23(6), 1060-72](https://www.nature.com/articles/cdd2015163)

Akt activation has been associated with proliferation, differentiation, survival and death of epithelial cells. Phosphorylation of Thr308 of Akt by phosphoinositide-dependent kinase 1 (PDK1) is critical for optimal stimulation of its kinase activity. However, the mechanism(s) regulating this process remain elusive. Here, we report that 14-3-3 proteins control Akt Thr308 phosphorylation during intestinal inflammation. Mechanistically, we found that IFN$\gamma$ and TNFα treatment induce degradation of the PDK1 inhibitor, 14-3-3η, in intestinal epithelial cells. This mechanism requires association of 14-3-3ζ with raptor in a process that triggers autophagy and leads to 14-3-3η degradation. Notably, inhibition of 14-3-3 function by the chemical inhibitor BV02 induces uncontrolled Akt activation, nuclear Akt accumulation and ultimately intestinal epithelial cell death. Our results suggest that 14-3-3 proteins control Akt activation and regulate its biological functions, thereby providing a new mechanistic link between cell survival and apoptosis of intestinal epithelial cells during inflammation.
:::

::: {.callout-note collapse="true"}
## IL-36 receptor promotes resolution of intestinal damage

Medina-Contreras O, Harusato A, Nishio H, Flannigan KL, Ngo V, Leoni G, Neumann PA, Geem D, Lili LN, Ramadas RA, Chassaing B, Gewirtz AT, Kohlmeier JE, Parkos CA, Towne JE, Nusrat A, Denning TL\
[*J Immunol* 196(1), 34-8](https://journals.aai.org/jimmunol/article/196/1/34/105174/Cutting-Edge-IL-36-Receptor-Promotes-Resolution-of)

IL-1 family members are central mediators of host defense. In this article, we show that the novel IL-1 family member IL-36$\gamma$ was expressed during experimental colitis and human inflammatory bowel disease. Germ-free mice failed to induce IL-36$\gamma$ in response to dextran sodium sulfate (DSS)-induced damage, suggesting that gut microbiota are involved in its induction. Surprisingly, IL-36R-deficient (Il1rl2(-/-)) mice exhibited defective recovery following DSS-induced damage and impaired closure of colonic mucosal biopsy wounds, which coincided with impaired neutrophil accumulation in the wound bed. Failure of Il1rl2(-/-) mice to recover from DSS-induced damage was associated with a profound reduction in IL-22 expression, particularly by colonic neutrophils. Defective recovery of Il1rl2(-/-) mice could be rescued by an aryl hydrocarbon receptor agonist, which was sufficient to restore IL-22 expression and promote full recovery from DSS-induced damage. These findings implicate the IL-36/IL-36R axis in the resolution of intestinal mucosal wounds.
:::

::: {.callout-note collapse="true"}
## IFN$\gamma$-induced suppression of $\beta$-catenin signaling: evidence for roles of Akt and 14.3.3$\zeta$

Nava P, Kamekura R, Quirós M, Medina-Contreras O, Hamilton RW, Kolegraff KN, Koch S, Candelario A, Romo-Parra H, Laur O, Hilgarth RS, Denning TL, Parkos CA, Nusrat A\
[*Mol Biol Cell* 25(19), 2894-904](https://www.molbiolcell.org/doi/10.1091/mbc.E13-09-0512?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed)

The proinflammatory cytokine interferon $\gamma$ (IFN$\gamma$) influences intestinal epithelial cell (IEC) homeostasis in a biphasic manner by acutely stimulating proliferation that is followed by sustained inhibition of proliferation despite continued mucosal injury. β-Catenin activation has been classically associated with increased IEC proliferation. However, we observed that IFN$\gamma$ inhibits IEC proliferation despite sustained activation of Akt/β-catenin signaling. Here we show that inhibition of Akt/β-catenin-mediated cell proliferation by IFN$\gamma$ is associated with the formation of a protein complex containing phosphorylated β-catenin 552 (pβ-cat552) and 14.3.3ζ. Akt1 served as a bimodal switch that promotes or inhibits β-catenin transactivation in response to IFN$\gamma$ stimulation. IFN$\gamma$ initially promotes β-catenin transactivation through Akt-dependent C-terminal phosphorylation of β-catenin to promote its association with 14.3.3ζ. Augmented β-catenin transactivation leads to increased Akt1 protein levels, and active Akt1 accumulates in the nucleus, where it phosphorylates 14.3.3ζ to translocate 14.3.3ζ/β-catenin from the nucleus, thereby inhibiting β-catenin transactivation and IEC proliferation. These results outline a dual function of Akt1 that suppresses IEC proliferation during intestinal inflammation.
:::

::: {.callout-note collapse="true"}
## Neutrophil-derived JAML inhibits repair of intestinal epithelial injury during acute inflammation

Weber DA, Sumagin R, McCall IC, Leoni G, Neumann PA, Andargachew R, Brazil JC, Medina-Contreras O, Denning TL, Nusrat A, Parkos CA\
[*Mucosal Immunol* 7(5), 1221-32](https://www.mucosalimmunology.org/article/S1933-0219(22)01131-X/fulltext)

Neutrophil transepithelial migration (TEM) during acute inflammation is associated with mucosal injury. Using models of acute mucosal injury in vitro and in vivo, we describe a new mechanism by which neutrophils infiltrating the intestinal mucosa disrupt epithelial homeostasis. We report that junctional adhesion molecule-like protein (JAML) is cleaved from neutrophil surface by zinc metalloproteases during TEM. Neutrophil-derived soluble JAML binds to the epithelial tight junction protein coxsackie-adenovirus receptor (CAR) resulting in compromised barrier and inhibition of wound repair, through decreased epithelial proliferation. The deleterious effects of JAML on barrier and wound repair are reversed with an anti-JAML monoclonal antibody that inhibits JAML-CAR binding. JAML released from transmigrating neutrophils across inflamed epithelia may thus promote recruitment of leukocytes and aid in clearance of invading microorganisms. However, sustained release of JAML under pathologic conditions associated with persistence of large numbers of infiltrated neutrophils would compromise intestinal barrier and inhibit mucosal healing. Thus, targeting JAML-CAR interactions may improve mucosal healing responses under conditions of dysregulated neutrophil recruitment.
:::

::: {.callout-note collapse="true"}
## Specific microbiota-induced intestinal Th17 differentiation requires MHC class II but not GALT and mesenteric lymph nodes

Geem D, Medina-Contreras O, McBride M, Newberry RD, Koni PA, Denning TL\
[*J Immunol* 193(1), 431-8](https://journals.aai.org/jimmunol/article/193/1/431/108704/Specific-Microbiota-Induced-Intestinal-Th17)

IL-17-expressing CD4+ T lymphocytes (Th17 cells) naturally reside in the intestine where specific cytokines and microbiota, such as segmented filamentous bacteria (SFB), promote their differentiation. Intestinal Th17 cells are thought to initially differentiate in the GALT and/or mesenteric lymph nodes upon Ag encounter and subsequently home to the lamina propria (LP) where they mediate effector functions. However, whether GALT and/or mesenteric lymph nodes are required for intestinal Th17 differentiation as well as how microbiota containing SFB regulate Ag-specific intestinal Th17 cells remain poorly defined. In this study, we observed that naive CD4+ T cells were abundant in the intestinal LP prior to weaning and that the accumulation of Th17 cells in response to microbiota containing SFB occurred in the absence of lymphotoxin-dependent lymphoid structures and the spleen. Furthermore, the differentiation of intestinal Th17 cells in the presence of microbiota containing SFB was dependent on MHC class II expression by CD11c+ cells. Lastly, the differentiation of Ag-specific Th17 cells required both the presence of cognate Ag and microbiota containing SFB. These findings suggest that microbiota containing SFB create an intestinal milieu that may induce Ag-specific Th17 differentiation against food and/or bacterial Ags directly in the intestinal LP.
:::

::: {.callout-note collapse="true"}
## Compromised intestinal epithelial barrier induces adaptive immune compensation that protects from colitis

Khounlotham M, Kim W, Peatman E, Nava P, Medina-Contreras O, Addis C, Koch S, Fournier B, Nusrat A, Denning TL, Parkos CA\
[*Immunity* 37(3), 563-73](https://www.cell.com/immunity/fulltext/S1074-7613(12)00380-9?_returnURL=https%3A%2F%2Flinkinghub.elsevier.com%2Fretrieve%2Fpii%2FS1074761312003809%3Fshowall%3Dtrue)

Mice lacking junctional adhesion molecule A (JAM-A, encoded by F11r) exhibit enhanced intestinal epithelial permeability, bacterial translocation, and elevated colonic lymphocyte numbers, yet do not develop colitis. To investigate the contribution of adaptive immune compensation in response to increased intestinal epithelial permeability, we examined the susceptibility of F11r(-/-)Rag1(-/-) mice to acute colitis. Although negligible contributions of adaptive immunity in F11r(+/+)Rag1(-/-) mice were observed, F11r(-/-)Rag1(-/-) mice exhibited increased microflora-dependent colitis. Elimination of T cell subsets and cytokine analyses revealed a protective role for TGF-β-producing CD4(+) T cells in F11r(-/-) mice. Additionally, loss of JAM-A resulted in elevated mucosal and serum IgA that was dependent upon CD4(+) T cells and TGF-β. Absence of IgA in F11r(+/+)Igha(-/-) mice did not affect disease, whereas F11r(-/-)Igha(-/-) mice displayed markedly increased susceptibility to acute injury-induced colitis. These data establish a role for adaptive immune-mediated protection from acute colitis under conditions of intestinal epithelial barrier compromise.
:::

::: {.callout-note collapse="true"}
## Isolation and characterization of dendritic cells and macrophages from the mouse intestine

Geem D, Medina-Contreras O, Kim W, Huang CS, Denning TL\
[*J Vis Exp* (63), e4040](https://www.jove.com/es/t/4040/isolation-characterization-dendritic-cells-macrophages-from-mouse)

Within the intestine reside unique populations of innate and adaptive immune cells that are involved in promoting tolerance towards commensal flora and food antigens while concomitantly remaining poised to mount inflammatory responses toward invasive pathogens. Antigen presenting cells, particularly DCs and macrophages, play critical roles in maintaining intestinal immune homeostasis via their ability to sense and appropriately respond to the microbiota. Efficient isolation of intestinal DCs and macrophages is a critical step in characterizing the phenotype and function of these cells. While many effective methods of isolating intestinal immune cells, including DCs and macrophages, have been described, many rely upon long digestions times that may negatively influence cell surface antigen expression, cell viability, and/or cell yield. Here, we detail a methodology for the rapid isolation of large numbers of viable, intestinal DCs and macrophages. Phenotypic characterization of intestinal DCs and macrophages is carried out by directly staining isolated intestinal cells with specific fluorescence-labeled monoclonal antibodies for multi-color flow cytometric analysis. Furthermore, highly pure DC and macrophage populations are isolated for functional studies utilizing CD11c and CD11b magnetic-activated cell sorting beads followed by cell sorting.
:::

::: {.callout-note collapse="true"}
## CX3CR1 regulates intestinal macrophage homeostasis, bacterial translocation, and colitogenic Th17 responses in mice

Medina-Contreras O, Geem D, Laur O, Williams IR, Lira SA, Nusrat A, Parkos CA, Denning TL\
[*J Clin Invest* 121(12), 4787-95](https://www.jci.org/articles/view/59150)

The two most common forms of inflammatory bowel disease (IBD), Crohn's disease and ulcerative colitis, affect approximately 1 million people in the United States. Uncontrolled APC reactivity toward commensal bacteria is implicated in the pathogenesis of the disease. A number of functionally distinct APC populations exist in the mucosal lamina propria (LP) below the intestinal epithelium, but their relative contributions to inflammation remain unclear. Here, we demonstrate in mice important roles for the chemokine receptor CX3CR1 in maintaining LP macrophage populations, preventing translocation of commensal bacteria to mesenteric lymph nodes (mLNs), and limiting colitogenic Th17 responses. CX3CR1 was found to be expressed in resident LP macrophages (defined as CD11b(+)F4/80(+)) but not DCs (defined as CD11c(+)CD103(+)). LP macrophage frequency and number were decreased in two strains of CX3CR1-knockout mice and in mice deficient in the CX3CR1 ligand CX3CL1. All these knockout strains displayed markedly increased translocation of commensal bacteria to mLNs. Additionally, the severity of DSS-induced colitis was dramatically enhanced in the knockout mice as compared with controls. Disease severity could be limited by either administration of neutralizing IL-17A antibodies or transfer of CX3CR1-sufficient macrophages. Our data thus suggest key roles for the CX3CR1/CX3CL1 axis in the intestinal mucosa; further clarification of CX3CR1 function will likely direct efforts toward therapeutic intervention for mucosal inflammatory disorders such as IBD.
:::

::: {.callout-note collapse="true"}
## Functional specializations of intestinal dendritic cell and macrophage subsets that control Th17 and regulatory T cell responses are dependent on the T cell/APC ratio, source of mouse strain, and regional localization

Denning TL, Norris BA, Medina-Contreras O, Manicassamy S, Geem D, Madan R, Karp CL, Pulendran B\
[*J Immunol* 187(2), 733-47](https://journals.aai.org/jimmunol/article/187/2/733/38769/Functional-Specializations-of-Intestinal-Dendritic)

Although several subsets of intestinal APCs have been described, there has been no systematic evaluation of their phenotypes, functions, and regional localization to date. In this article, we used 10-color flow cytometry to define the major APC subsets in the small and large intestine lamina propria. Lamina propria APCs could be subdivided into CD11c(+)CD11b(-), CD11c(+)CD11b(+), and CD11c(dull)CD11b(+) subsets. CD11c(+)CD11b(-) cells were largely CD103(+)F4/80(-) dendritic cells (DCs), whereas the CD11c(+)CD11b(+) subset comprised CD11c(+)CD11b(+)CD103(+)F4/80(-) DCs and CD11c(+)CD11b(+)CD103(-)F4/80(+) macrophage-like cells. The majority of CD11c(dull)CD11b(+) cells were CD103(-)F4/80(+) macrophages. Although macrophages were more efficient at inducing Foxp3(+) regulatory T (T(reg)) cells than DCs, at higher T cell/APC ratios, all of the DC subsets efficiently induced Foxp3(+) T(reg) cells. In contrast, only CD11c(+)CD11b(+)CD103(+) DCs efficiently induced Th17 cells. Consistent with this, the regional distribution of CD11c(+)CD11b(+)CD103(+) DCs correlated with that of Th17 cells, with duodenum \> jejunum \> ileum \> colon. Conversely, CD11c(+)CD11b(-)CD103(+) DCs, macrophages, and Foxp3(+) T(reg) cells were most abundant in the colon and scarce in the duodenum. Importantly, however, the ability of DC and macrophage subsets to induce Foxp3(+) T(reg) cells versus Th17 cells was strikingly dependent on the source of the mouse strain. Thus, DCs from C57BL/6 mice from Charles River Laboratories (that have segmented filamentous bacteria, which induce robust levels of Th17 cells in situ) were more efficient at inducing Th17 cells and less efficient at inducing Foxp3(+) T(reg) cells than DCs from B6 mice from The Jackson Laboratory. Thus, the functional specializations of APC subsets in the intestine are dependent on the T cell/APC ratio, regional localization, and source of the mouse strain.
:::

::: {.callout-note collapse="true"}
## CRTAM: A molecule involved in epithelial cell adhesion

Garay E, Patiño-López G, Islas S, Alarcón L, Canche-Pool E, Valle-Rios R, Medina-Contreras O, Granados G, Chávez-Munguía B, Juaristi E, Ortiz-Navarrete V, González-Mariscal L\
[*J Cell Biochem* 111(1), 111-22](https://onlinelibrary.wiley.com/doi/10.1002/jcb.22673)

Class I-restricted T cell associated molecule (CRTAM) is a member of the immunoglobulin superfamily that complies with the structural characteristics of the JAM family of proteins and is phylogenetically more closely related to nectin-like proteins. Here we demonstrate for the first time, that CRTAM is expressed in epithelial cells along the lateral membrane and is important for early cell-cell contacts and cell-substrate interactions. CRTAM is sensitive to intermediate filament disruption and treatment of monolayers with soluble CRTAM enhances cell-cell dissociation and lowers transepithelial electrical resistance. Incubation of newly plated cells with anti-CRTAM antibody decreases the formation of cell aggregates and promotes cell detachment. Co-cultures of epithelial cells and fibroblasts that lack CRTAM expression and in vitro binding assays, demonstrate the participation of CRTAM in homotypic and heterotypic trans-interactions. Hence we conclude that CRTAM is a molecule involved in epithelial cell adhesion.
:::

::: {.callout-note collapse="true"}
## Role of CRTAM during mouse early T lymphocytes development

Medina-Contreras O, Soldevila G, Patiño-Lopez G, Canche-Pool E, Valle-Rios R, Ortiz-Navarrete V\
[*Dev Comp Immunol* 34(2), 196-202](https://www.sciencedirect.com/science/article/pii/S0145305X09002018?via%3Dihub)

CRTAM was reported as a novel receptor expressed in activated NKT and CD8 T lymphocytes. However, we have recently shown that it is also expressed in several non-immune tissues. In opposition to what has been stated for lymphoid cells, CRTAM expression is constitutive in epithelia, suggesting a role in cell-cell interactions. Given the importance of cell interactions during T lymphocyte development, we evaluated CRTAM during T lymphocyte ontogeny. Here we show that CRTAM has an unexpected constitutive expression in adult thymocytes and, remarkably, it is sustained during all stages of thymocyte development. CRTAM expression is restricted to CD8 and all DN subpopulations, with a consistent pattern from E13.5 stage to adult mice. Blocking CRTAM interaction with CADM1 impairs thymus growth, uncovering a novel role in thymus development, with a consequent impact in thymocyte maturation. Thus, CRTAM interaction with CADM1 is involved in structural maintenance of the thymic lobes.
:::

::: {.callout-note collapse="true"}
## B cell precursors are targets for *Salmonella* infection

Castro-Eguiluz D, Pelayo R, Rosales-Garcia V, Rosales-Reyes R, Alpuche-Aranda C, Ortiz-Navarrete V\
*Microb Pathog* 47(1), 52-6
:::

::: {.callout-note collapse="true"}
## Characterization of CRTAM gene promoter: AP-1 transcription factor control its expression in human T CD8 lymphocytes

Valle-Rios R, Patiño-Lopez G, Medina-Contreras O, Canche-Pool E, Recillas-Targa F, Lopez-Bayghen E, Zlotnik A, Ortiz-Navarrete V\
[*Mol Immunol* 46(16), 3379-87](https://www.sciencedirect.com/science/article/abs/pii/S0161589009006166?via%3Dihub)

Class-I MHC-restricted T-cell associated molecule (CRTAM) is a member of the Nectin-like adhesion molecule family. It is rapidly induced in NK, NKT and CD8(+) T cells. Interaction with its ligand Nectin-like 2 results in increased secretion of IFN-gamma by activated CD8(+) T lymphocytes. Through sequential bioinformatic analyses of the upstream region of the human CRTAM gene, we detected cis-elements potentially important for CRTAM gene transcription. Analyzing 2kb upstream from the ATG translation codon by mutation analysis in conjunction with luciferase reporter assays, electrophoretic mobility shift assay (EMSA) and supershift assays, we identified an AP-1 binding site, located at 1.4kb from the ATG translation codon of CRTAM gene as an essential element for CRTAM expression in activated but not resting human CD8(+) T cells. CRTAM expression was reduced in activated CD8(+) T cells treated with the JNK inhibitor SP600125, indicating that CRTAM expression is driven by the JNK-AP-1 signaling pathway. This study represents the first CRTAM gene promoter analysis in human T cells and indicates that AP-1 is a positive transcriptional regulator of this gene, a likely important finding because CRTAM has recently been shown to play a role in IFN-gamma and IL-17 production and T cell proliferation.
:::

::: {.callout-note collapse="true"}
## Endometriosis and discouragement of immunology cytotoxic characteristics

Hernández Guerrero CA, Tlapanco Barba R, Ramos Pérez C, Velázquez Ramírez N, Castro Eguiluz D, Cérbulo Vázquez A.\
*Ginecol Obstet Mex* 71, 559-74

Objective: To determine the immunology kind of response Th1 (cytotoxic) or Th2 (humoral) prevailing at peripheral and peritoneal environment at endometriosis women (ENW). Study design: Observational, transverse, analytical, retrospective, cases and controls. Material and methods: Cooperative and cytotoxic lymphocytes obtained from peritoneal fluid (PF) and peripheral blood (PB) were used to determine IFN-gamma and IL-2 intracellular synthesis at ENW. IFN-gamma, IL-2, IL-4 and IL-10 concentration were determined at PF, PB at ENW and fertile women (FERW). Results were analyzed by ANOVA, t student and Mann-Whitney tests, accepting p \< 0.05, as a statistic difference. Results: Peritoneal environment of ENW shows a smaller intracellular synthesis of IFN-gamma and IL-2 at cooperative and cytotoxic T lymphocytes, as in the PF at ENW. The decrease is associated to a smaller percentage of activated, cooperative T lymphocytes and NK cells (p \< 0.05, at all the variable), versus FERW. This phenomenon is observed more stressed at the III and IV pathology degree. Conclusions: ENW show a peritoneal environment with a smaller immunology cytotoxic capacity, versus FERW. The discouragement of the immunology cytotoxic capacity increases associated to the pathology intensity.
:::