---
title: 'Tinción para citometría de flujo'
subtitle: 'Inmunoensayos'

author:
  name: omclab
  email: omedina@himfg.edu.mx

abstract: |
  Mantener un cultivo celular *in vitro* en condiciones apropiadas para su crecimiento, propagación o almacenamiento para los fines que se requiera.
categories: [CULTIVO CELULAR]
thanks: |
  **Version** `Inicial` 2022-02

format:
  html: default
  fancy-doc-pdf: default
number-sections: false
title-block-banner: "#0047AB"
title-block-banner-color: "#FFFFFF"
crossref:
  chapters: true

date: last-modified
lang: es-MX
bibliography: refs.bib

execute:
  eval: false
  echo: fenced
  freeze: auto
---

{{< pagebreak >}}

## Descripción del Protocolo

::: callout-note
### Pasos

-   Tinción de viabilidad

    - [ ] Agregar 1.5 x10^6^ células en tubos para citometría de flujo, centrifugar a 1500rpm/4°C/5 minutos.

    - [ ] **Lavar**: Agregar 3ml de PBS 1x. Centrifugar a 1500 rpm/4°C/5 minutos. Decantar el sobrenadante.

    - [ ] Agregar la tinción de viabilidad e incubar 30 minutos/obscuridad/4ºC.

    - [ ] Lavar.

-   Tinción de superficie

    - [ ] Resuspender las células en 200$\mu$l de buffer de FACS.

    - [ ] Agregar 2$\mu$l $\gamma$-globulinas humanas e incubar 20 minutos/obscuridad/4ºC.

    - [ ] Agregar anticuerpos de superficie titulados en buffer de FACS, incubar 30 minutos/obscuridad/4ºC.

    - [ ] **Lavar**: Agregar 3ml de buffer de FACS. Centrifugar a 1500rpm/4°C/5 minutos. Decantar el sobrenadante.

    - [ ] Agregar solución fijadora (500$\mu$L), incubar 20 minutos/obscuridad/4ºC.

    - [ ] Lavar.

    - [ ] Resuspender las células en 200$\mu$l de buffer de FACS.

    - [ ] Analizar la muestra inmediatamente o en los 2 días posteriores a la tinción.

-   Tinción intracelular

    - [ ] Realizar tinción de superficie.

    - [ ] Resuspender las células en 1ml de buffer de permeabilización, incubar 20 minutos/obscuridad/4ºC.

    - [ ] **Lavar**: Agregar 3ml de buffer de permeabilización. Centrifugar a 1500 rpm/4°C/5 minutos. Decantar el sobrenadante.

    - [ ] Agregar anticuerpos intracelulares en buffer de permeabilización e incubar 30 minutos/obscuridad/4ºC.

    - [ ]  Lavar.

    - [ ] Resuspender en 200$\mu$L de buffer de FACS.

    - [ ] Analizar la muestra inmediatamente o en los 2 días posteriores a la tinción.
:::

::: {.callout-caution collapse="true"}
### Notas

-   Conservar las muestras teñidas en refrigeración hasta realizar el análisis. Máximo 1 semana.
:::

\newpage

### Diagrama de Flujo

```{mermaid}
%%| fig-width: 5
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```

### Anexos

#### Soluciones

| Reactivo | Volumen | Concentración |
|----------|----------|----------|
| PBS      | 490ml    | 98%      |
| SFB      | 10ml     | 2%       |

: Solución de FACS

#### Definiciones

SFB
: suero fetal bovino

PBS
: buffer de fosfatos

### Documentos de referencia

::: {#refs}
:::
