---
title: Adipocitos
date: 2024-06-17
author:
  name: Oscar Medina Contreras
  id: omc
  orcid: 0000-0002-4432-7780
  email: omedina@himfg.edu.mx
  url: www.omclab.org
  affiliation: 
    - name: Hospital Infantil de México
      city: Ciudad de Mexico
      state: CDMX
      url: www.himfg.edu.mx
lang: es-MX
number-sections: false
title-block-banner: "#0047AB"
title-block-banner-color: "#FFFFFF"
crossref:
  chapters: true
---

# Diferenciación de adipocitos

`UIEEN-PL-025` <kbd>CULTIVO CELULAR</kbd>

### Propósito

Diferenciar células 3T3-L1 a adipocitos.

### Alcance

Este procedimiento involucra a todo el personal técnico, científico y
estudiantes que realicen cultivo celular y que necesiten diferenciar células 3T3-L1 a adipocitos en la
`Unidad de Investigación Epidemiológica en Endocrinología y Nutrición del Hospital Infantil de México Federico Gómez`.

### Políticas de operación, normas y lineamientos

Es responsabilidad de todo el personal técnico, científico y estudiantes
adscritos a la Unidad de Investigación Epidemiológica en Endocrinología
y Nutrición del Hospital Infantil de México Federico Gómez conocer y dar
seguimiento a este procedimiento. Los residuos de tipo CRETI
(Corrosivas, Reactivas, Explosivas, Toxicas e Inflamables) se deberán
eliminar con base en su clasificación y especificaciones de manejo según
la Norma Oficial Mexicana NOM-087-ECOL-SSA1-2002; así como sus
características intrínsecas y su toxicidad al ambiente según la NOM-052-
SEMARNAT-2005.

### Descripción del Protocolo

::: callout-note
### Pasos

- Descongelar células 3T3-L1. Esperar a que el criovial se descongele un 60%, y colocarlo en un tubo de 15 mL con medio de crecimiento.
-	Centrifugar a 600 rpm por 5 minutos.
-	Decantar el sobrenadante, con los residuos de medio que quedan el tubo, resuspender las células.
-	Al tubo, agregar 3.5-5 mL o 7.5-10 mL para una botella de 25 cm2 y 75 cm2, respectivamente y transferir las células a su respectiva botella. Incubar.
-	Una vez que las células presenten una confluencia mayor al 80%, cosecharlas. Decantar el medio, lavar la monocapa de células con 3 mL de PBS 1X dos veces, agregar 2 mL de tripsina e incubar a 37°C por 5 minutos, agregar 2 mL de medio de crecimiento.
-	Contar las células por el método de hemocitometría. Se sugiere realizar una dilución 1:2.
-	 En placas tratadas de 6 pozos, colocar 1x105 células por pozo, en 2 mL de medio de crecimiento. Incubar por aproximadamente 18 horas o hasta que se forme la monocapa de células.
-	Una vez formada la monocapa, retirar todo el medio y agregar 3mL de MD-I, incubar.
-	Retirar el 70% del medio y agregar 3mL de MD-II, incubar por 4 días.
-	Transcurrido el tiempo, retirar el 70% de MD-II y añadir 3mL de MD-III, incubar por 4 días.
-	Terminado el tiempo de incubación con el MD-III, retirar el 70% del medio y agregar 3mL de medio de crecimiento e incubar por 1 semana. Si durante este tiempo las células requieren cambio de medio, realizarlo de la manera ya antes descrita.
:::

::: {.callout-caution collapse="true"}
### Notas

- No realizar diferenciaciones con un pase celular arriba de 10.
Las incubaciones se deben realizar a 37°C, 5% CO2.
Durante la diferenciación de las células se observará un cambio morfológico, aproximadamente en el día 12.
La presencia de gotas de lípidos podrá ser observadas en las células a partir del día 8.
Durante el proceso de diferenciación no debe perderse más del 10% de células.
Los volúmenes que se mencionan es para los pozos de una placa de 6 pozos, estos volúmenes se pueden adecuar dependiendo del tamaño de pozo que se ocupe.
El número de células es para el tamaño de pozo de una placa de 6 pozos, se puede adecuar el número de células de acuerdo al tamaño de la superficie en donde se realizará la diferenciación, la confluencia deberá ser de 80-90%.

:::

### Diagrama de Flujo

![Figura 1.
Diagrama de flujo](images/adipo.png){width="25%"}

### Anexos

<details open>

<summary>Soluciones</summary>

Preparación de medios.
a)	Medio de crecimiento

Medio DMEM + 10% SFB + antibiótico/antimicótico + l-glutamina
b)	Medios de diferenciación(MD)
La siguiente tabla es descrita para 3 Ml de m, es decir para un pozo.
Al medio de crecimiento se le adicionara los reactivos necesarios para preparar los medios de diferenciación

	MD-I	MD-II	MD-III
Dexamentasona 25 μM	30 μL	30 μL	---
IBMX 125 μM	12 μL	12 μL	---
Insulina 300 UI/mL	1 μL	1 μL	1 μL
Rosiglitazona 20 mM	---	3 μL de una dilución 1:10 (9 μL de medio de crecimiento + 1 μL de rosiglitazona 20 Mm) 	---


</details>

### Documentos de [-@sec-ref]

Zebisch K, Voigt V, Wabitsch M, Brandsch M. Protocol for effective differentiation of 3T3-L1 cells to adipocytes. Analytical biochemistry. 2012;425(1):88-90.