---
title: "Tinción para citometría de flujo"
subtitle: Inmunoensayos
author: UIEEN_IM-PL-011*v03*
lang: es
---

### Propósito

Realizar una tinción de superficie e intracelular de células vivas para su posterior análisis por citometría de flujo. 
La citometría de flujo permite el análisis de células de manera individual. 
Se pueden analizar moléculas en la superficie, el citoplasma o el núcleo. 
Además, existen reactivos que permiten la detección de ácidos nucleicos o iones para evaluar proliferación, muerte, activación, metabolismo.

### Alcance

Este procedimiento involucra a todo el personal técnico, científico y estudiantes que quieran realizar una tinción de superficie e intracelular de células linfoides vivas para su posterior análisis por citometría de flujo en el Laboratorio de Inmunometabolismo la Unidad de Investigación Epidemiológica en Endocrinología y Nutrición del Hospital Infantil de México Federico Gómez.

### Políticas de operación, normas y lineamientos

Es responsabilidad de todo el personal técnico, científico y estudiantes
adscritos a la Unidad de Investigación Epidemiológica en Endocrinología
y Nutrición del Hospital Infantil de México Federico Gómez conocer y dar
seguimiento a este procedimiento. Los residuos de tipo CRETI
(Corrosivas, Reactivas, Explosivas, Toxicas e Inflamables) se deberán
eliminar con base en su clasificación y especificaciones de manejo según
la Norma Oficial Mexicana NOM-087-ECOL-SSA1-2002; así como sus
características intrínsecas y su toxicidad al ambiente según la NOM-052-
SEMARNAT-2005. Se debe de dar seguimiento a la norma oficial mexicana
NOM-087-ECOL-1995, que establece los requisitos para la separación,
envasado, almacenamiento, recolección, transporte, tratamiento y
disposición final de los residuos peligrosos biológico-infecciosos, que
se generan en establecimientos que presten atención médica.

### Historial

|versión| Elaborado | Revisado | Autorizado |
|:-:|:-:|:-:|:-:|
||**estudiante**|**postdoc**|**Chayanne**|
|[3] 07.24.25|       ||       |
|[2] 12.10.21||||
|[1] 08.23.16||||

: {tbl-colwidths="[16,28,28,28]"}

\newpage

## Descripción del Protocolo

::: callout-note
### Pasos

-   Tinción de viabilidad

    - [ ] Agregar 1.5 x10^6^ células en tubos para citometría de flujo, centrifugar a 1500rpm/4°C/5 minutos.

    - [ ] **Lavar**: Agregar 3ml de PBS 1x. Centrifugar a 1500 rpm/4°C/5 minutos. Decantar el sobrenadante.

    - [ ] Agregar la tinción de viabilidad e incubar 30 minutos/obscuridad/4ºC.

    - [ ] Lavar.

-   Tinción de superficie

    - [ ] Resuspender las células en 200$\mu$l de buffer de FACS.

    - [ ] Agregar 2$\mu$l $\gamma$-globulinas humanas e incubar 20 minutos/obscuridad/4ºC.

    - [ ] Agregar anticuerpos de superficie titulados en buffer de FACS, incubar 30 minutos/obscuridad/4ºC.

    - [ ] **Lavar**: Agregar 3ml de buffer de FACS. Centrifugar a 1500rpm/4°C/5 minutos. Decantar el sobrenadante.

    - [ ] Agregar solución fijadora (500$\mu$L), incubar 20 minutos/obscuridad/4ºC.

    - [ ] Lavar.

    - [ ] Resuspender las células en 200$\mu$l de buffer de FACS.

    - [ ] Analizar la muestra inmediatamente o en los 2 días posteriores a la tinción.

-   Tinción intracelular

    - [ ] Realizar tinción de superficie.

    - [ ] Resuspender las células en 1ml de buffer de permeabilización, incubar 20 minutos/obscuridad/4ºC.

    - [ ] **Lavar**: Agregar 3ml de buffer de permeabilización. Centrifugar a 1500 rpm/4°C/5 minutos. Decantar el sobrenadante.

    - [ ] Agregar anticuerpos intracelulares en buffer de permeabilización e incubar 30 minutos/obscuridad/4ºC.

    - [ ]  Lavar.

    - [ ] Resuspender en 200$\mu$L de buffer de FACS.

    - [ ] Analizar la muestra inmediatamente o en los 2 días posteriores a la tinción.
:::

::: {.callout-caution collapse="true"}
### Notas

-   Conservar las muestras teñidas en refrigeración hasta realizar el análisis. Máximo 1 semana.
:::

\newpage

### Diagrama de Flujo

```{mermaid}
%%| fig-width: 5
flowchart LR
  A[Hard edge] --> B(Round edge)
  B --> C{Decision}
  C --> D[Result one]
  C --> E[Result two]
```

### Anexos

#### Soluciones

| Reactivo | Volumen | Concentración |
|----------|----------|----------|
| PBS      | 490ml    | 98%      |
| SFB      | 10ml     | 2%       |

: Solución de FACS

#### Definiciones

SFB
: suero fetal bovino

PBS
: buffer de fosfatos

### Documentos de referencia

::: {#refs}
:::
