
# Conteo y viabilidad celular

`UIEEN-PL-004` <kbd>CULTIVO CELULAR</kbd>

### Propósito

Mantener un cultivo de celular *in vitro* en condiciones apropiadas para
su crecimiento, propagación o almacenamiento para los fines que se
requiera.

### Alcance

Este procedimiento involucra a todo el personal técnico, científico y
estudiantes que realicen cultivo celular y que deseen congelar,
descongelar, contar y determinar la viabilidad celular en la
`Unidad de Investigación Epidemiológica en Endocrinología y Nutrición del Hospital Infantil de México Federico Gómez`.

### Políticas de operación, normas y lineamientos

Es responsabilidad de todo el personal técnico, científico y estudiantes
adscritos a la Unidad de Investigación Epidemiológica en Endocrinología
y Nutrición del Hospital Infantil de México Federico Gómez conocer y dar
seguimiento a este procedimiento. Los residuos de tipo CRETI
(Corrosivas, Reactivas, Explosivas, Toxicas e Inflamables) se deberán
eliminar con base en su clasificación y especificaciones de manejo según
la Norma Oficial Mexicana NOM-087-ECOL-SSA1-2002; así como sus
características intrínsecas y su toxicidad al ambiente según la NOM-052-
SEMARNAT-2005.

### Descripción del Protocolo

::: callout-note
### Pasos

-   Limpiar el hemocitómetro con alcohol al 70%. Esperar a que esté
    secos por completo y colocar el cubreobjetos en de la rejilla.

-   Mezclar 10$\mu$l de una suspensión celular uniforme con 90$\mu$l de
    azul de tripano 0.4%. Incubar 2 min.

-   Colocar 10$\mu$l de la mezcla bajo el cubreobjetos y observar al
    microscopio con una magnificación 40x.

-   Contar las células sin colorante presentes en los cuadrantes 1, 2, 4
    y 5 del hemocitómetro (Fig. 1) sin considerar las células que toquen
    las líneas.

-   Calcular concentración de células:

$células/ml = \frac{células * 10^{5}}{volúmen}$

-   Calcular la viabilidad celular

$viabilidad = \frac{células}{total}*{100}$

-   Limpiar el hemocitómetro con alcohol 70% y secar.
:::

::: {.callout-caution collapse="true"}
### Notas

-   
:::

### Diagrama de Flujo

![Figura 1.
Hemocitometro](https://www.omclab.org/images/R.png){width="25%"}

![Figura 2. Conteo
celular](https://www.omclab.org/images/R.png){width="25%"}

![Figura 3. Viabilidad
celular](https://www.omclab.org/images/R.png){width="25%"}

### Anexos

<details open>

<summary>Soluciones</summary>

</details>

### Documentos de [-@sec-ref]
